#!/bin/sh
# Create the canonical archive used by the public Luce release.
#
# The release tree is disposable.  Normalize the facts that otherwise come
# from the builder (permissions, timestamps, ownership, traversal order, and
# gzip's header) so rebuilding one source commit produces identical bytes.
#
# The tree this packages has to hold up its own end.  Two things inside a
# macOS product would otherwise vary per assembly and neither is normalized
# here, because by the time a file reaches this script it is already written:
# the linker's LC_UUID, and the ad-hoc code signature's identifier, which is
# taken from the name the link wrote through.  `src/apps/native.zig` settles
# both at link time (`-no_uuid`, `-final_output`).
set -eu

if [ "$#" -ne 3 ]; then
    echo "usage: www/luce/archive.sh TREE_ROOT ARCHIVE_ROOT OUTPUT" >&2
    exit 1
fi

tree_root=$1
archive_root=$2
output=$3

case "$tree_root:$output" in
    *'\n'*|*'\r'*)
        echo "luce archive: paths may not contain newlines" >&2
        exit 1
        ;;
esac
if [ ! -d "$tree_root/$archive_root" ]; then
    echo "luce archive: missing archive root: $tree_root/$archive_root" >&2
    exit 1
fi

command -v chmod >/dev/null 2>&1 || { echo "luce archive: chmod is required" >&2; exit 1; }
command -v find >/dev/null 2>&1 || { echo "luce archive: find is required" >&2; exit 1; }
command -v grep >/dev/null 2>&1 || { echo "luce archive: grep is required" >&2; exit 1; }
command -v gzip >/dev/null 2>&1 || { echo "luce archive: gzip is required" >&2; exit 1; }
command -v sed >/dev/null 2>&1 || { echo "luce archive: sed is required" >&2; exit 1; }
command -v sort >/dev/null 2>&1 || { echo "luce archive: sort is required" >&2; exit 1; }
command -v tar >/dev/null 2>&1 || { echo "luce archive: tar is required" >&2; exit 1; }
command -v touch >/dev/null 2>&1 || { echo "luce archive: touch is required" >&2; exit 1; }

umask 022
parent=$(dirname "$output")
mkdir -p "$parent"
work=$(mktemp -d "${TMPDIR:-/tmp}/luce-archive.XXXXXX")
cleanup() {
    rm -rf "$work"
}
trap cleanup 0 HUP INT TERM

# Archive roots are generated by release.sh and contain no user-controlled
# names.  Refuse anything else anyway, because links and device nodes would
# make the archive non-reproducible and unsafe to install.
if find "$tree_root/$archive_root" -mindepth 1 \( ! -type d ! -type f \) -print -quit | grep -q .; then
    echo "luce archive: tree contains a link or special file" >&2
    exit 1
fi

# Preserve only the executable bit.  Every directory and ordinary file gets
# a stable mode, regardless of the umask or ownership of the build machine.
find "$tree_root/$archive_root" -type d -exec chmod 755 {} +
find "$tree_root/$archive_root" -type f \( -perm -100 -o -perm -010 -o -perm -001 \) -exec chmod 755 {} +
find "$tree_root/$archive_root" -type f ! \( -perm -100 -o -perm -010 -o -perm -001 \) -exec chmod 644 {} +

# The canonical timestamp is intentionally independent of the builder's
# clock.  It is recorded in BUILD-MANIFEST by release.sh.
find "$tree_root/$archive_root" -exec touch -h -t 200001010000.00 {} +

members="$work/members"
archive_tar="$work/archive.tar"
find "$tree_root" -mindepth 1 -print |
    sed "s#^$tree_root/##" |
    LC_ALL=C sort >"$members"

case "$(tar --version 2>&1 | head -n 1)" in
    *'GNU tar'*)
        tar --no-recursion --owner=0 --group=0 --numeric-owner \
            -cf "$archive_tar" -C "$tree_root" -T "$members"
        ;;
    *)
        # macOS ships bsdtar.  Keep the explicit metadata flags here rather
        # than depending on the invoking user's numeric uid or group name.
        tar --no-recursion --no-xattrs --no-mac-metadata \
            --uid 0 --gid 0 --uname root --gname wheel \
            -cf "$archive_tar" -C "$tree_root" -T "$members"
        ;;
esac

temporary_output="$work/$(basename "$output")"
gzip -n -c "$archive_tar" >"$temporary_output"
mv "$temporary_output" "$output"
