#!/bin/sh
# Build luce.luciaos.com into www/luce/out.
#
# The toolchain comes first, because the site is generated by running
# it: every Luce sample on every page is compiled with build/luce and
# run with build/loom, and the output printed under a sample is the
# output that run produced.  A sample that stops working stops this
# script.
#
#   ./www/luce/build.sh          build the toolchain, then the site
#   ./www/luce/build.sh --fast   trust the toolchain already in build/
set -e

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)

if [ "${1:-}" != "--fast" ]; then
    echo "==> toolchain"
    (cd "$root" && ./build.sh)
fi

for tool in luce loom; do
    if [ ! -x "$root/build/$tool" ]; then
        echo "luce site: $root/build/$tool is missing — run ./build.sh first" >&2
        exit 1
    fi
done

echo "==> generator"
mkdir -p "$here/work"
zig_global_cache="$here/work/zig-global-cache"
site_assets="$here/work/assets"
mkdir -p "$zig_global_cache"
rm -rf "$site_assets"
mkdir -p "$site_assets"
cp -R "$here/assets/." "$site_assets/"
cp "$root/www/shared/core.css" "$site_assets/core.css"
zig build-exe "$here/src/main.zig" \
    -O ReleaseSafe \
    --name lucedoc \
    --global-cache-dir "$zig_global_cache" \
    -femit-bin="$here/work/lucedoc"

echo "==> generator tests"
zig test "$here/src/main.zig" --global-cache-dir "$zig_global_cache"

echo "==> pages"
cd "$here"
./work/lucedoc \
    --content "$here/content" \
    --assets "$site_assets" \
    --out "$here/out" \
    --toolchain "$root/build" \
    --work "$here/work/samples" \
    --repository "$root"
cmp "$root/www/shared/core.css" "$here/out/assets/core.css"

echo "==> release"
release_version=$(tr -d '[:space:]' <"$root/VERSION")
release_source="$here/install/$release_version/install.sh"
release_work="$here/work/release"
release_prefix="$release_work/prefix"
release_tree="$release_work/luce-$release_version"
release_output="$here/out/install/$release_version"
archive_name="luce-${release_version}-macos-aarch64.tar.gz"
termui_version=$(awk '/^[[:space:]]*termui[[:space:]]*:/ { print $2; exit }' "$root/examples/editor/luce.yaml")
termui_source="$root/packages/termui-$termui_version"
extension_source="$root/tools/vscode-luce"
extension_version=$(awk -F'"' '/^[[:space:]]*"version"[[:space:]]*:/ { print $4; exit }' "$extension_source/package.json")
extension_id="luciaos.luce-language"
extension_tree="$release_tree/share/vscode/extensions/$extension_id-$extension_version"

if [ ! -x "$release_source" ]; then
    echo "luce site: missing executable installer for release $release_version: $release_source" >&2
    exit 1
fi
if ! grep -Fq "version=$release_version" "$release_source"; then
    echo "luce site: installer version does not match VERSION ($release_version)" >&2
    exit 1
fi
if ! grep -Fq "extension_version=$extension_version" "$release_source"; then
    echo "luce site: installer extension version does not match package.json ($extension_version)" >&2
    exit 1
fi
if [ -z "$termui_version" ] || [ ! -f "$termui_source/luce.yaml" ] || [ ! -f "$termui_source/termui.luc" ]; then
    echo "luce site: termui $termui_version is incomplete" >&2
    exit 1
fi
if ! grep -Fq "termui_version=$termui_version" "$release_source"; then
    echo "luce site: installer termui version does not match the editor manifest ($termui_version)" >&2
    exit 1
fi
if [ -z "$extension_version" ] || [ ! -f "$extension_source/package.json" ] || [ ! -f "$extension_source/extension.js" ]; then
    echo "luce site: VS Code extension package is incomplete" >&2
    exit 1
fi

# Build the public release in a target-specific prefix.  The regular site
# build above uses the host toolchain; this second build is intentionally
# explicit so a release cannot accidentally contain host binaries.
rm -rf "$release_work"
mkdir -p "$release_prefix" "$release_tree/bin" "$release_tree/lib" "$extension_tree/syntaxes" "$release_output"
macos_sdk=$(xcrun --sdk macosx --show-sdk-path)
(cd "$root" && zig build \
    --prefix "$release_prefix" \
    -Dtarget=aarch64-macos \
    -Doptimize=ReleaseSafe \
    -Dsysroot="$macos_sdk" \
    --global-cache-dir "$zig_global_cache" \
    --summary all)

for tool in luce loom editor; do
    if [ ! -x "$release_prefix/$tool" ]; then
        echo "luce site: ARM64 release is missing $tool" >&2
        exit 1
    fi
    cp "$release_prefix/$tool" "$release_tree/bin/$tool"
done
for library in libluce_rt.a libluce_start.a; do
    if [ ! -f "$release_prefix/lib/$library" ]; then
        echo "luce site: ARM64 release is missing lib/$library" >&2
        exit 1
    fi
    cp "$release_prefix/lib/$library" "$release_tree/lib/$library"
done
termui_release="$release_tree/lib/termui-$termui_version"
mkdir -p "$termui_release"
cp "$termui_source/luce.yaml" "$termui_release/luce.yaml"
for module in termui model input layout canvas view runtime; do
    cp "$termui_source/$module.luc" "$termui_release/$module.luc"
done
printf '%s\n' "$release_version" >"$release_tree/VERSION"
# Keep the editor support in the same checked release.  The installer copies
# this dependency-free extension into VS Code's per-user extension shelf.
cp "$extension_source/package.json" "$extension_tree/package.json"
cp "$extension_source/extension.js" "$extension_tree/extension.js"
cp "$extension_source/language-configuration.json" "$extension_tree/language-configuration.json"
cp "$extension_source/README.md" "$extension_tree/README.md"
cp "$extension_source/syntaxes/luce.tmLanguage.json" "$extension_tree/syntaxes/luce.tmLanguage.json"
cp "$release_source" "$release_output/install.sh"
chmod +x "$release_output/install.sh"
tar -czf "$release_output/$archive_name" \
    -C "$release_work" "luce-$release_version"
(cd "$release_output" && shasum -a 256 "$archive_name" >"$archive_name.sha256")
tar -tzf "$release_output/$archive_name" >/dev/null
echo "release: $release_output/$archive_name"

echo "==> installer smoke"
smoke="$release_work/smoke"
smoke_install="$smoke/luce"
smoke_extensions="$smoke/extensions"
smoke_profile="$smoke/profile"
smoke_program="$smoke/hello.luc"
mkdir -p "$smoke"

run_installer_smoke() {
    LUCE_INSTALL_BASE_URL="file://$release_output" \
    LUCE_INSTALL_DIR="$smoke_install" \
    LUCE_INSTALL_EDITOR_EXTENSIONS_DIR="$smoke_extensions" \
    LUCE_INSTALL_PROFILE="$smoke_profile" \
    LUCE_INSTALL_NO_PATH=0 \
        "$release_output/install.sh"
}

# Run twice: a release installer promises replacement with a fresh copy and
# must not duplicate PATH entries or leave a stale editor extension behind.
run_installer_smoke
run_installer_smoke

test "$("$smoke_install/bin/luce" --version)" = "luce $release_version"
test "$("$smoke_install/bin/loom" --version)" = "loom $release_version"
test -x "$smoke_install/bin/editor"
test -f "$smoke_install/lib/termui-$termui_version/termui.luc"
test -f "$smoke_extensions/$extension_id-$extension_version/package.json"
test "$(grep -Fc "$smoke_install/bin" "$smoke_profile")" -eq 1
test "$(grep -Fc "$smoke_install/lib" "$smoke_profile")" -eq 1

printf '%s\n' 'func main():' '    print("installer works")' >"$smoke_program"
(cd "$smoke" && "$smoke_install/bin/luce" build hello.luc)
test "$("$smoke/hello")" = "installer works"
(cd "$smoke" && "$smoke_install/bin/luce" build hello.luc --emit=library -o hello.lc)
test "$("$smoke_install/bin/loom" run "$smoke/hello.lc")" = "installer works"
printf '%s\n' 'name: smoke' 'version: 0.1.0' 'packages:' "  termui: $termui_version" >"$smoke/luce.yaml"
printf '%s\n' \
    'import termui' \
    'func main():' \
    '    let frame = termui.snapshot(termui.Panel("ok", termui.Label("ready")), 3, 10)' \
    '    print(frame.line(1))' >"$smoke/package_app.luc"
(cd "$smoke" && . "$smoke_profile" && "$smoke_install/bin/luce" build package_app.luc)
test "$("$smoke/package_app")" = "│ready   │"
echo "installer: fresh replacement, PATH, package shelf, editor support, executable, and library run passed"

echo "==> done: $here/out"
