#!/bin/sh
# Build luce.luciaos.com into www/luce/out.
#
# The toolchain comes first, because the site is generated by running
# it: every Luce sample on every page is compiled with build/luce and
# run with build/loom, and the output printed under a sample is the
# output that run produced.  A sample that stops working stops this
# script.
#
#   ./www/luce/build.sh          build the toolchain, then the site
#   ./www/luce/build.sh --fast   trust the toolchain already in build/
set -e

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)

if [ "${1:-}" != "--fast" ]; then
    echo "==> toolchain"
    (cd "$root" && ./build.sh)
fi

for tool in luce loom; do
    if [ ! -x "$root/build/$tool" ]; then
        echo "luce site: $root/build/$tool is missing — run ./build.sh first" >&2
        exit 1
    fi
done

echo "==> generator"
mkdir -p "$here/work"
zig_global_cache="$here/work/zig-global-cache"
site_assets="$here/work/assets"
mkdir -p "$zig_global_cache"
rm -rf "$site_assets"
mkdir -p "$site_assets"
cp -R "$here/assets/." "$site_assets/"
cp "$root/www/shared/core.css" "$site_assets/core.css"
zig build-exe "$here/src/main.zig" \
    -O ReleaseSafe \
    --name lucedoc \
    --global-cache-dir "$zig_global_cache" \
    -femit-bin="$here/work/lucedoc"

echo "==> generator tests"
zig test "$here/src/main.zig" --global-cache-dir "$zig_global_cache"

echo "==> pages"
cd "$here"
./work/lucedoc \
    --content "$here/content" \
    --assets "$site_assets" \
    --out "$here/out" \
    --toolchain "$root/build" \
    --work "$here/work/samples" \
    --repository "$root"
cmp "$root/www/shared/core.css" "$here/out/assets/core.css"
"$here/test-installer.sh"
echo "==> done: $here/out"
echo "    Release archives are built separately by ./www/luce/release.sh."
