#!/bin/sh
# Build loom.luciaos.com into loomsite/out.
#
# The site is six pages of prose about one binary, so the machinery is
# six pages' worth: a manifest (`pages`), one HTML fragment per page
# under `content/`, and this script, which wraps each fragment in the
# one shell every page wears and writes the tab bar and the
# Previous/Next links out of the manifest.  Adding a page is a row and
# a file; nothing else has to be told.
#
# Then it checks every internal link — the file it names and the
# anchor it names — and fails if one of them is not there.  A
# documentation site whose own links rot is a site nobody trusts.
#
#   ./loomsite/build.sh
#
# There is deliberately no Luce verification here, which is the one
# thing that makes this different from `site/`.  luce.luciaos.com is
# generated by *running* the toolchain over every sample on it; this
# site is about the tool rather than the language, and what it shows
# is mostly shell transcripts.  The few Luce programs it does show are
# checked by hand with `build/luce check` and marked as checked in the
# page they appear on.  When that stops being enough — when there are
# enough samples that a hand is the wrong instrument — this script is
# where the checking goes, and `site/src/verify.zig` is how it is
# done.
set -e

here=$(cd "$(dirname "$0")" && pwd)
out=$here/out

rm -rf "$out"
mkdir -p "$out"

# ---------------------------------------------------------------- manifest

# Comment and blank lines out, so the manifest can explain itself.
manifest=$(grep -v '^#' "$here/pages" | grep -v '^[[:space:]]*$')

field() {
    printf '%s\n' "$1" | cut -d'	' -f"$2"
}

# The tab bar, once per page, with the current page marked.  Built as
# a here-string rather than a loop inside a loop because it is the
# same bar on every page but for one class.
tabs() {
    current=$1
    depth=$2
    printf '%s\n' "$manifest" | while IFS= read -r row; do
        slug=$(field "$row" 1)
        label=$(field "$row" 2)
        if [ -z "$slug" ]; then
            href=$depth
        else
            href=$depth$slug/
        fi
        if [ "$slug" = "$current" ]; then
            printf '<a class="here" href="%s">%s</a>\n' "$href" "$label"
        else
            printf '<a href="%s">%s</a>\n' "$href" "$label"
        fi
    done
}

# ------------------------------------------------------------------- pages

count=$(printf '%s\n' "$manifest" | wc -l | tr -d ' ')
index=0

printf '%s\n' "$manifest" | while IFS= read -r row; do
    index=$((index + 1))
    slug=$(field "$row" 1)
    title=$(field "$row" 3)
    description=$(field "$row" 4)

    if [ -z "$slug" ]; then
        page=$out/index.html
        source=$here/content/index.html
        depth=./
    else
        mkdir -p "$out/$slug"
        page=$out/$slug/index.html
        source=$here/content/$slug.html
        depth=../
    fi

    if [ ! -f "$source" ]; then
        echo "build: $source is missing — the manifest names a page with no content" >&2
        exit 1
    fi

    # Previous and next, by position in the manifest.
    previous=$(printf '%s\n' "$manifest" | sed -n "$((index - 1))p")
    next=$(printf '%s\n' "$manifest" | sed -n "$((index + 1))p")

    {
        cat <<HEAD
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$(if [ -z "$slug" ]; then printf '%s' "$title"; else printf '%s &middot; loom' "$title"; fi)</title>
<meta name="description" content="$description">
<link rel="stylesheet" href="${depth}assets/style.css">
<link rel="icon" href="${depth}assets/mark.svg" type="image/svg+xml">
<script>try{var t=localStorage.getItem("luce-theme");if(t)document.documentElement.dataset.theme=t}catch(e){}</script>
</head>
<body>
<a class="skip" href="#content">Skip to content</a>

<header class="top">
<a class="mark" href="$depth">loom</a>
<nav class="tabs">
$(tabs "$slug" "$depth")
</nav>
<div class="tools">
<a class="cross" href="https://luce.luciaos.com">Luce</a>
<a class="cross" href="https://luciaos.com">LuciaOS</a>
<button id="theme" type="button" aria-label="Switch between light and dark">&#9681;</button>
</div>
</header>

<div class="shell">
<main id="content">
<article>
<h1>$title</h1>
HEAD
        # `@/` in a fragment means the site root.  A fragment does not
        # know how deep the page it becomes will sit, and the out/
        # tree has to open from a file:// path as well as from a
        # domain root, so neither an absolute `/` nor a hand-counted
        # `../` will do.
        sed "s|@/|$depth|g" "$source"
        printf '</article>\n'

        if [ -n "$previous" ] || [ -n "$next" ]; then
            printf '<nav class="seq">\n'
            if [ -n "$previous" ]; then
                p_slug=$(field "$previous" 1)
                p_title=$(field "$previous" 3)
                if [ -z "$p_slug" ]; then p_href=$depth; else p_href=$depth$p_slug/; fi
                printf '<a class="back" href="%s"><span>Previous</span>%s</a>\n' "$p_href" "$p_title"
            else
                printf '<span></span>\n'
            fi
            if [ -n "$next" ]; then
                n_slug=$(field "$next" 1)
                n_title=$(field "$next" 3)
                if [ -z "$n_slug" ]; then n_href=$depth; else n_href=$depth$n_slug/; fi
                printf '<a class="on" href="%s"><span>Next</span>%s</a>\n' "$n_href" "$n_title"
            fi
            printf '</nav>\n'
        fi

        cat <<FOOT
</main>
</div>

<footer>
<p>loom is part of <a href="https://luciaos.com">LuciaOS</a>, beside <a href="https://luce.luciaos.com">Luce</a>, the language it runs. Everything on these pages describes the binary as it is built from the repository today; <a href="${depth}direction/">Direction</a> is the one page that talks about what is not built yet, and says so.</p>
</footer>
<script src="${depth}assets/site.js" defer></script>
</body>
</html>
FOOT
    } > "$page"

    echo "    $page"
done

cp -R "$here/assets" "$out/assets"

# ------------------------------------------------------------------- links

# Every href that is not external must name a file in the output tree,
# and where it names an anchor that anchor must exist in that file.
echo "==> links"
broken=0
for page in $(find "$out" -name '*.html'); do
    directory=$(dirname "$page")
    for href in $(grep -o 'href="[^"]*"' "$page" | sed 's/^href="//; s/"$//'); do
        case $href in
            http://*|https://*|mailto:*|'#') continue ;;
        esac
        anchor=""
        case $href in
            \#*) target=$page; anchor=${href#\#} ;;
            *\#*) target=$directory/${href%%\#*}; anchor=${href#*\#} ;;
            *) target=$directory/$href ;;
        esac
        case $target in */) target=${target}index.html ;; esac
        if [ ! -f "$target" ]; then
            echo "  broken: $page -> $href (no $target)" >&2
            broken=$((broken + 1))
            continue
        fi
        if [ -n "$anchor" ] && ! grep -q "id=\"$anchor\"" "$target"; then
            echo "  broken: $page -> $href (no anchor #$anchor in $target)" >&2
            broken=$((broken + 1))
        fi
    done
done
if [ "$broken" != 0 ]; then
    echo "build: $broken broken link(s)" >&2
    exit 1
fi

echo "==> done: $out ($count pages)"
