#!/bin/sh
# Build luce.luciaos.com into site/out.
#
# The toolchain comes first, because the site is generated by running
# it: every Luce sample on every page is compiled with build/luce and
# run with build/loom, on both engines, and the output printed under a
# sample is the output that run produced.  A sample that stops working
# stops this script.
#
#   ./site/build.sh          build the toolchain, then the site
#   ./site/build.sh --fast   trust the toolchain already in build/
set -e

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)

if [ "$1" != "--fast" ]; then
    echo "==> toolchain"
    (cd "$root" && ./build.sh)
fi

for tool in luce loom; do
    if [ ! -x "$root/build/$tool" ]; then
        echo "site: $root/build/$tool is missing — run ./build.sh first" >&2
        exit 1
    fi
done

echo "==> generator"
mkdir -p "$here/work"
zig build-exe "$here/src/main.zig" \
    -O ReleaseSafe \
    --name lucedoc \
    -femit-bin="$here/work/lucedoc"

echo "==> generator tests"
zig test "$here/src/main.zig"

echo "==> pages"
cd "$here"
./work/lucedoc \
    --content "$here/content" \
    --assets "$here/assets" \
    --out "$here/out" \
    --toolchain "$root/build" \
    --work "$here/work/samples" \
    --repository "$root"

echo "==> done: $here/out"
