//! The self-written backend — Luce IR emitted straight to machine
//! code, no MIR, no C (docs/SPEED.md §16-17).
//!
//! This is the sovereignty engine growing behind the same seam as
//! the others: it emits against `native.abi` (the State word offsets
//! and the address table), produces the same hermetic spans as the
//! MIR engine — no host address in the bytes, every call target,
//! constant, and float read from the table — and runs through the
//! same `image.map` + `native.runCode` machinery, under the same
//! oracle.  MIR remains the racing baseline; the runner falls from
//! this backend to MIR to the interpreter per program.
//!
//! Milestone 2 transfers MIR's whole aarch64 core: every arm of
//! native.zig's lowering has its twin here — floats as a second
//! register class, Int(Float) with the NaN and range guards,
//! multi-function calls over the C ABI, the ownership serial and
//! return loosening, the full generic-service marshaling for
//! heap-shaped instructions, all the fast services, inline view
//! and string access, and typed local zeros.  The gate is
//! `native.supported()` narrowed by this backend's own ABI limits,
//! so it never claims a program MIR could not run.  Targets:
//! aarch64 macOS/Linux (the encoder is OS-blind; image.map does the
//! OS work); x86-64 next; Windows once image.zig grows VirtualAlloc.
//!
//! Code shape: locals pinned in callee-saved registers (x20-x26 for
//! values, d8-d12 for floats; frame slots beyond), block-local
//! temporaries in small spilling pools (x9-x12, d13-d15) — sound
//! because the IR guarantees registers never cross blocks.  Values
//! stay lazy until a use forces them, which is what immediate
//! forms, constant-divisor guard elision, and direct pinned reads
//! fall out of; comparisons feeding the adjacent branch fuse to
//! cmp + b.cond; producers feeding the adjacent local_set of a
//! pinned local write it directly.  x19 holds the State, x28 the
//! frame serial; x13/x14 and d16 are transient scratch the
//! allocator never owns; x16 is the call target.

const std = @import("std");
const builtin = @import("builtin");
const ir = @import("ir.zig");
const types = @import("types.zig");
const native = @import("native.zig");
const image = @import("image.zig");
const codegen_x86 = @import("codegen_x86.zig");

const Allocator = std.mem.Allocator;
const abi = native.abi;
const AddressTable = native.AddressTable;

/// The self-written backend covers whichever ISA this loom was built
/// for: aarch64 in this file, x86-64 in codegen_x86.zig, both against
/// the same seams.  `supported`/`compile` dispatch by arch.
pub const available = (builtin.cpu.arch == .aarch64 or builtin.cpu.arch == .x86_64) and image.supported;
const on_x86 = builtin.cpu.arch == .x86_64;

/// Whether the self-written backend is complete and proven enough on
/// this target to be loom's *default* engine (LOOM_ENGINE=auto),
/// rather than the opt-in racer.  aarch64 carries the whole language
/// (milestone 2); x86-64 is still the scalar-core milestone 1, so it
/// stays opt-in and auto keeps MIR there.  The runner asks this
/// instead of hardcoding targets — backend maturity is the backend's
/// own concern, not the ladder's.
pub const mature_default = available and
    builtin.cpu.arch == .aarch64 and builtin.os.tag == .macos;

/// Arguments travel in registers only: x1-x7 for values, d0-d7 for
/// floats.  Wider signatures fall back to MIR (which speaks the full
/// C ABI) through the runner's engine ladder.
const max_value_arguments = 7;
const max_float_arguments = 8;

/// The exact self-written generator which produced a cached image.
/// Embedding this file is intentional: changing an encoder, lowering,
/// register policy, or even a relevant constant changes the identity
/// without relying on a manually maintained version number.
const generator_identity: u64 = blk: {
    @setEvalBranchQuota(2_000_000);
    // On x86-64 the emitter lives in codegen_x86.zig, so its source
    // decides the generated bytes; fold it in so a cached image
    // invalidates when the x86 encoder changes.
    const source = if (on_x86)
        @embedFile("codegen.zig") ++ @embedFile("codegen_x86.zig")
    else
        @embedFile("codegen.zig");
    break :blk generatorIdentityFor(source, builtin.zig_version_string);
};

fn hashIdentityPart(hasher: *std.hash.Wyhash, part: []const u8) void {
    var length: [8]u8 = undefined;
    std.mem.writeInt(u64, &length, @intCast(part.len), .little);
    hasher.update(&length);
    hasher.update(part);
}

fn generatorIdentityFor(source: []const u8, zig_version: []const u8) u64 {
    var hasher = std.hash.Wyhash.init(0);
    hashIdentityPart(&hasher, "luce-self-aarch64-generator-v1");
    hashIdentityPart(&hasher, source);
    hashIdentityPart(&hasher, zig_version);
    return hasher.final();
}

fn fingerprintFor(generator: u64, runtime_abi: u64) u64 {
    var hasher = std.hash.Wyhash.init(0);
    hashIdentityPart(&hasher, "luce-self-aarch64-image-v1");
    hashIdentityPart(&hasher, @tagName(builtin.cpu.arch));
    hashIdentityPart(&hasher, @tagName(builtin.os.tag));
    hasher.update(std.mem.asBytes(&generator));
    hasher.update(std.mem.asBytes(&runtime_abi));
    return hasher.final();
}

/// Backend-specific image identity.  The runtime half covers State,
/// payload, address-table, service, target, and module ABI changes;
/// the generator half covers this source and the Zig compiler.  The
/// domain tag prevents MIR and self-written images from interchanging.
pub fn fingerprint() u64 {
    return fingerprintFor(generator_identity, native.fingerprint());
}

/// Cheap program/code key for a warm image lookup.  The portable
/// module already determines the IR exactly, so domain-separating its
/// bytes with the generator identity avoids re-emitting code merely to
/// validate the cache.
pub fn imageTextHash(encoded_module: []const u8) u64 {
    return std.hash.Wyhash.hash(generator_identity, encoded_module);
}

/// Whether the whole program fits this backend: everything MIR's
/// core takes, minus the shapes this emitter's ABI does not carry
/// yet.
pub fn supported(program: *const ir.Program) bool {
    if (!available) return false;
    if (on_x86) return codegen_x86.supported(program);
    if (!native.supported(program)) return false;
    for (program.functions) |*function| {
        // Frame slots use a scaled 12-bit immediate; share MIR's
        // audited bound so both native engines cap stack allocation.
        if (function.locals.len + function.instructions.len > native.max_function_slots) return false;
        var value_arguments: usize = 0;
        var float_arguments: usize = 0;
        for (function.locals[0..function.parameter_count]) |local| {
            if (local.local_type == .float) {
                float_arguments += 1;
            } else {
                value_arguments += 1;
            }
        }
        if (value_arguments > max_value_arguments) return false;
        if (float_arguments > max_float_arguments) return false;
    }
    return true;
}

/// Compile the program to one hermetic span per function.  Callers
/// map the spans executable (image.map) and run them with
/// native.runCode — the same path a cached image takes.  Assumes
/// supported() said yes.
pub fn compile(arena: Allocator, program: *const ir.Program) native.RunError![]const []const u8 {
    if (on_x86) return codegen_x86.compile(arena, program);
    const table = try AddressTable.collect(arena, program);
    const spans = try arena.alloc([]const u8, program.functions.len);
    for (program.functions, spans, 0..) |*function, *span, index| {
        var emitter: Emitter = .{
            .arena = arena,
            .program = program,
            .table = table,
            .function = function,
            .function_index = @intCast(index),
        };
        try emitter.emitFunction();
        span.* = emitter.code.items;
    }
    return spans;
}

// ---------------------------------------------------------------------------
// The emitter
// ---------------------------------------------------------------------------

/// A pending branch to a mark not yet bound.
const FixupKind = enum { jump26, cond19 };

const Fixup = struct {
    at: usize,
    mark: u32,
    kind: FixupKind,
};

/// One trap exit: sets the trap triple in the State, returns default.
const TrapSite = struct {
    mark: u32,
    code: ir.TrapCode,
    instruction: u32,
};

/// Where an IR register's value currently is.  Constants and
/// local_get results stay lazy until a use forces them — that is
/// what immediate operand forms and guard elision hang on.
const Location = union(enum) {
    /// Not defined yet, or dead past its last use.
    nowhere,
    /// In a value scratch-pool register the allocator owns.
    register: u5,
    /// In a float scratch-pool register the allocator owns.
    fregister: u5,
    /// Spilled to (or only ever in) its frame slot.
    slot,
    /// A lazy integer/boolean constant.
    immediate: i64,
    /// A lazy table load (a constant string's descriptor address, or
    /// a float constant's bits) at this byte offset off the State.
    table: u64,
    /// A lazy local_get: valid while the local's version matches —
    /// a local_set in between materializes live aliases first.
    alias: struct { local: u32, version: u32 },
};

const scratch_pool = [_]u5{ 9, 10, 11, 12 };
const float_pool = [_]u5{ 13, 14, 15 }; // d13-d15, callee-saved
const pinned_pool = [_]u5{ 20, 21, 22, 23, 24, 25, 26 };
const float_pinned_pool = [_]u5{ 8, 9, 10, 11, 12 }; // d8-d12, callee-saved

const Emitter = struct {
    arena: Allocator,
    program: *const ir.Program,
    table: AddressTable,
    function: *const ir.Function,
    function_index: u32,
    code: std.ArrayList(u8) = .empty,
    marks: std.ArrayList(?usize) = .empty,
    fixups: std.ArrayList(Fixup) = .empty,
    sites: std.ArrayList(TrapSite) = .empty,
    block_marks: []u32 = &.{},
    epilogue: u32 = 0,
    propagate: u32 = 0,
    frame_size: u64 = 0,
    uses_floats: bool = false,

    // Analysis (emission order = block order, one position per item).
    positions: []u32 = &.{},
    last_use: []u32 = &.{},
    use_count: []u32 = &.{},

    // Allocation state.
    location: []Location = &.{},
    scratch_owner: [scratch_pool.len]?ir.Register = @splat(null),
    float_owner: [float_pool.len]?ir.Register = @splat(null),
    pinned: []?u5 = &.{},
    local_version: []u32 = &.{},
    position: u32 = 0,
    /// A comparison whose flags are still live for the next item.
    pending_compare: ?struct { register: ir.Register, condition: u4 } = null,
    /// A local_set already performed by its producer writing the
    /// pinned register directly; the set itself only bumps the
    /// version.
    pending_absorb: ?u32 = null,
    /// The block being emitted, for fallthrough elision.
    current_block: u32 = 0,

    // -- aarch64 conditions ------------------------------------------------

    const eq: u4 = 0x0;
    const ne: u4 = 0x1;
    const hs: u4 = 0x2;
    const mi: u4 = 0x4;
    const vs: u4 = 0x6;
    const hi: u4 = 0x8;
    const ls: u4 = 0x9;
    const ge: u4 = 0xA;
    const lt: u4 = 0xB;
    const gt: u4 = 0xC;
    const le: u4 = 0xD;

    const state: u5 = 19;
    const serial: u5 = 28;
    const zr: u5 = 31;
    /// Transient scratch the allocator never owns.
    const helper: u5 = 13;
    const helper2: u5 = 14;
    const fhelper: u5 = 16; // d16, caller-saved, never allocated

    fn word(self: *Emitter, encoded: u32) error{OutOfMemory}!void {
        try self.code.appendSlice(self.arena, &std.mem.toBytes(std.mem.nativeToLittle(u32, encoded)));
    }

    fn here(self: *const Emitter) usize {
        return self.code.items.len;
    }

    fn newMark(self: *Emitter) error{OutOfMemory}!u32 {
        try self.marks.append(self.arena, null);
        return @intCast(self.marks.items.len - 1);
    }

    fn bind(self: *Emitter, mark: u32) void {
        self.marks.items[mark] = self.here();
    }

    fn typeOf(self: *const Emitter, register: ir.Register) types.Type {
        return self.function.result_types[register];
    }

    fn isFloat(self: *const Emitter, register: ir.Register) bool {
        return self.typeOf(register) == .float;
    }

    // -- encodings, integer ------------------------------------------------

    fn movz(self: *Emitter, rd: u5, chunk: u16, half: u2) !void {
        try self.word(0xD2800000 | @as(u32, half) << 21 | @as(u32, chunk) << 5 | rd);
    }

    fn movk(self: *Emitter, rd: u5, chunk: u16, half: u2) !void {
        try self.word(0xF2800000 | @as(u32, half) << 21 | @as(u32, chunk) << 5 | rd);
    }

    /// Any 64-bit value: movz of the low half-word, movk of each
    /// non-zero higher one.
    fn materialize(self: *Emitter, rd: u5, value: u64) !void {
        try self.movz(rd, @truncate(value), 0);
        inline for (1..4) |half| {
            const chunk: u16 = @truncate(value >> (16 * half));
            if (chunk != 0) try self.movk(rd, chunk, half);
        }
    }

    fn movReg(self: *Emitter, rd: u5, rm: u5) !void {
        try self.word(0xAA0003E0 | @as(u32, rm) << 16 | rd);
    }

    fn loadWord(self: *Emitter, rt: u5, rn: u5, byte_offset: u64) !void {
        const scaled: u12 = @intCast(byte_offset / 8);
        try self.word(0xF9400000 | @as(u32, scaled) << 10 | @as(u32, rn) << 5 | rt);
    }

    fn storeWord(self: *Emitter, rt: u5, rn: u5, byte_offset: u64) !void {
        const scaled: u12 = @intCast(byte_offset / 8);
        try self.word(0xF9000000 | @as(u32, scaled) << 10 | @as(u32, rn) << 5 | rt);
    }

    fn loadByte(self: *Emitter, rt: u5, rn: u5, byte_offset: u64) !void {
        try self.word(0x39400000 | @as(u32, @intCast(byte_offset)) << 10 | @as(u32, rn) << 5 | rt);
    }

    fn storeByte(self: *Emitter, rt: u5, rn: u5, byte_offset: u64) !void {
        try self.word(0x39000000 | @as(u32, @intCast(byte_offset)) << 10 | @as(u32, rn) << 5 | rt);
    }

    /// ldr rt, [state, offset] — offsets can pass the immediate
    /// range, so the offset goes through the transient helper.
    fn loadTable(self: *Emitter, rt: u5, offset: u64) !void {
        try self.materialize(helper, offset);
        try self.word(0xF8606800 | @as(u32, helper) << 16 | @as(u32, state) << 5 | rt);
    }

    fn loadSlot(self: *Emitter, rt: u5, slot: usize) !void {
        try self.loadWord(rt, 31, @as(u64, slot) * 8);
    }

    fn storeSlot(self: *Emitter, rt: u5, slot: usize) !void {
        try self.storeWord(rt, 31, @as(u64, slot) * 8);
    }

    fn addImmediate(self: *Emitter, rd: u5, rn: u5, immediate: u12) !void {
        try self.word(0x91000000 | @as(u32, immediate) << 10 | @as(u32, rn) << 5 | rd);
    }

    fn subImmediate(self: *Emitter, rd: u5, rn: u5, immediate: u12) !void {
        try self.word(0xD1000000 | @as(u32, immediate) << 10 | @as(u32, rn) << 5 | rd);
    }

    fn branchTo(self: *Emitter, mark: u32) !void {
        try self.fixups.append(self.arena, .{ .at = self.here(), .mark = mark, .kind = .jump26 });
        try self.word(0x14000000);
    }

    fn branchCond(self: *Emitter, condition: u4, mark: u32) !void {
        // Keep the conditional displacement local and let an imm26
        // jump carry the real target.  Inverting the condition makes
        // the ordinary fallthrough skip the veneer.
        try self.word(0x54000040 | @as(u32, condition ^ 1)); // b.!cond +8
        try self.branchTo(mark);
    }

    fn branchZero(self: *Emitter, rt: u5, mark: u32, when_zero: bool) !void {
        const inverse: u32 = if (when_zero) 0xB5000040 else 0xB4000040;
        try self.word(inverse | rt); // cbnz/cbz +8
        try self.branchTo(mark);
    }

    fn compareRegisters(self: *Emitter, rn: u5, rm: u5) !void {
        try self.word(0xEB00001F | @as(u32, rm) << 16 | @as(u32, rn) << 5);
    }

    /// cmp rn, #imm — subs for a non-negative immediate, cmn for a
    /// negative one (flags of rn - imm either way).
    fn compareImmediate(self: *Emitter, rn: u5, immediate: i64) !void {
        if (immediate >= 0) {
            try self.word(0xF100001F | @as(u32, @intCast(immediate)) << 10 | @as(u32, rn) << 5);
        } else {
            try self.word(0xB100001F | @as(u32, @intCast(-immediate)) << 10 | @as(u32, rn) << 5);
        }
    }

    fn setCond(self: *Emitter, rd: u5, condition: u4) !void {
        try self.word(0x9A9F07E0 | @as(u32, condition ^ 1) << 12 | rd);
    }

    fn callRegister(self: *Emitter, rn: u5) !void {
        try self.word(0xD63F0000 | @as(u32, rn) << 5);
    }

    // -- encodings, float --------------------------------------------------

    fn fmovRegs(self: *Emitter, rd: u5, rn: u5) !void {
        try self.word(0x1E604000 | @as(u32, rn) << 5 | rd);
    }

    /// fmov dN, xM — also the +0.0 zero via xzr.
    fn fmovFromValue(self: *Emitter, rd: u5, rn: u5) !void {
        try self.word(0x9E670000 | @as(u32, rn) << 5 | rd);
    }

    fn floadWord(self: *Emitter, rt: u5, rn: u5, byte_offset: u64) !void {
        const scaled: u12 = @intCast(byte_offset / 8);
        try self.word(0xFD400000 | @as(u32, scaled) << 10 | @as(u32, rn) << 5 | rt);
    }

    fn fstoreWord(self: *Emitter, rt: u5, rn: u5, byte_offset: u64) !void {
        const scaled: u12 = @intCast(byte_offset / 8);
        try self.word(0xFD000000 | @as(u32, scaled) << 10 | @as(u32, rn) << 5 | rt);
    }

    fn floadTable(self: *Emitter, rt: u5, offset: u64) !void {
        try self.materialize(helper, offset);
        // ldr d, [state, helper]
        try self.word(0xFC606800 | @as(u32, helper) << 16 | @as(u32, state) << 5 | rt);
    }

    fn floadSlot(self: *Emitter, rt: u5, slot: usize) !void {
        try self.floadWord(rt, 31, @as(u64, slot) * 8);
    }

    fn fstoreSlot(self: *Emitter, rt: u5, slot: usize) !void {
        try self.fstoreWord(rt, 31, @as(u64, slot) * 8);
    }

    fn fcompare(self: *Emitter, rn: u5, rm: u5) !void {
        try self.word(0x1E602000 | @as(u32, rm) << 16 | @as(u32, rn) << 5);
    }

    // -- the trap protocol -------------------------------------------------

    fn trapSite(self: *Emitter, code: ir.TrapCode, instruction: u32) error{OutOfMemory}!u32 {
        const mark = try self.newMark();
        try self.sites.append(self.arena, .{ .mark = mark, .code = code, .instruction = instruction });
        return mark;
    }

    /// After a call: any recorded trap propagates.  Reads through the
    /// helper — the pools may be holding values.
    fn trapCheck(self: *Emitter) !void {
        try self.loadWord(helper, state, abi.trap_offset);
        try self.branchZero(helper, self.propagate, false);
    }

    // -- analysis ----------------------------------------------------------

    fn operandsOf(instruction: *const ir.Instruction, buffer: *[2]ir.Register) []const ir.Register {
        switch (instruction.*) {
            .binary => |operation| {
                buffer[0] = operation.left;
                buffer[1] = operation.right;
                return buffer[0..2];
            },
            .unary => |operation| {
                buffer[0] = operation.operand;
                return buffer[0..1];
            },
            .convert => |operation| {
                buffer[0] = operation.operand;
                return buffer[0..1];
            },
            .local_set => |set| {
                buffer[0] = set.value;
                return buffer[0..1];
            },
            .branch => |branching| {
                buffer[0] = branching.condition;
                return buffer[0..1];
            },
            .ret => |value| {
                if (value) |register| {
                    buffer[0] = register;
                    return buffer[0..1];
                }
                return buffer[0..0];
            },
            .call => |call| return call.arguments,
            .intrinsic => |call| return call.arguments,
            .heap_new => |new| return new.dims,
            .struct_make => |make| return make.fields,
            .struct_get => |get| {
                buffer[0] = get.target;
                return buffer[0..1];
            },
            .struct_set => |set| {
                buffer[0] = set.target;
                buffer[1] = set.value;
                return buffer[0..2];
            },
            .object_bind => |bound| {
                buffer[0] = bound.value;
                return buffer[0..1];
            },
            .object_unbind => |unbound| {
                buffer[0] = unbound.value;
                return buffer[0..1];
            },
            else => return buffer[0..0],
        }
    }

    fn analyze(self: *Emitter) error{OutOfMemory}!void {
        const function = self.function;
        const count = function.instructions.len;
        self.positions = try self.arena.alloc(u32, count);
        self.last_use = try self.arena.alloc(u32, count);
        self.use_count = try self.arena.alloc(u32, count);
        self.location = try self.arena.alloc(Location, count);
        @memset(self.last_use, 0);
        @memset(self.use_count, 0);
        @memset(self.location, .nowhere);
        var position: u32 = 0;
        for (function.blocks) |block| {
            for (block.items) |item| {
                self.positions[item] = position;
                var buffer: [2]ir.Register = undefined;
                for (operandsOf(&function.instructions[item], &buffer)) |operand| {
                    self.last_use[operand] = position;
                    self.use_count[operand] += 1;
                }
                position += 1;
            }
        }
        for (function.result_types) |result| {
            if (result == .float) self.uses_floats = true;
        }
        for (function.locals) |local| {
            if (local.local_type == .float) self.uses_floats = true;
        }
    }

    // -- the allocator -----------------------------------------------------

    fn slotOf(self: *const Emitter, register: ir.Register) usize {
        return self.function.locals.len + register;
    }

    fn poolIndexOf(register: u5) usize {
        for (scratch_pool, 0..) |candidate, index| {
            if (candidate == register) return index;
        }
        unreachable;
    }

    fn floatPoolIndexOf(register: u5) usize {
        for (float_pool, 0..) |candidate, index| {
            if (candidate == register) return index;
        }
        unreachable;
    }

    /// A free value-pool register, evicting the longest-lived owner
    /// if the pool is full.  Registers in `locked` (operands mid-use)
    /// are never evicted.
    fn allocScratch(self: *Emitter, owner: ir.Register, locked: []const u5) error{OutOfMemory}!u5 {
        for (scratch_pool, 0..) |candidate, index| {
            if (self.scratch_owner[index] == null and !contains(locked, candidate)) {
                self.scratch_owner[index] = owner;
                return candidate;
            }
        }
        var victim_index: ?usize = null;
        for (scratch_pool, 0..) |candidate, index| {
            if (contains(locked, candidate)) continue;
            const resident = self.scratch_owner[index].?;
            if (victim_index == null or
                self.last_use[resident] > self.last_use[self.scratch_owner[victim_index.?].?])
            {
                victim_index = index;
            }
        }
        const index = victim_index.?; // pool > lockable operands
        const evicted = self.scratch_owner[index].?;
        try self.storeSlot(scratch_pool[index], self.slotOf(evicted));
        self.location[evicted] = .slot;
        self.scratch_owner[index] = owner;
        return scratch_pool[index];
    }

    fn allocFloat(self: *Emitter, owner: ir.Register, locked: []const u5) error{OutOfMemory}!u5 {
        for (float_pool, 0..) |candidate, index| {
            if (self.float_owner[index] == null and !contains(locked, candidate)) {
                self.float_owner[index] = owner;
                return candidate;
            }
        }
        var victim_index: ?usize = null;
        for (float_pool, 0..) |candidate, index| {
            if (contains(locked, candidate)) continue;
            const resident = self.float_owner[index].?;
            if (victim_index == null or
                self.last_use[resident] > self.last_use[self.float_owner[victim_index.?].?])
            {
                victim_index = index;
            }
        }
        const index = victim_index.?;
        const evicted = self.float_owner[index].?;
        try self.fstoreSlot(float_pool[index], self.slotOf(evicted));
        self.location[evicted] = .slot;
        self.float_owner[index] = owner;
        return float_pool[index];
    }

    fn contains(haystack: []const u5, needle: u5) bool {
        for (haystack) |candidate| {
            if (candidate == needle) return true;
        }
        return false;
    }

    fn release(self: *Emitter, register: ir.Register) void {
        switch (self.location[register]) {
            .register => |physical| self.scratch_owner[poolIndexOf(physical)] = null,
            .fregister => |physical| self.float_owner[floatPoolIndexOf(physical)] = null,
            else => {},
        }
        self.location[register] = .nowhere;
    }

    /// Free operands whose last use is the current position.
    fn freeDead(self: *Emitter, operands: []const ir.Register) void {
        for (operands) |operand| {
            if (self.last_use[operand] <= self.position) self.release(operand);
        }
    }

    /// The value in a physical register of its class, forcing lazy
    /// locations.  Pinned-local reads return the pinned register
    /// itself (never evictable, never a dest).
    fn operandRegister(self: *Emitter, register: ir.Register, locked: []const u5) error{OutOfMemory}!u5 {
        if (self.isFloat(register)) return self.operandFloat(register, locked);
        switch (self.location[register]) {
            .register => |physical| return physical,
            .fregister => unreachable,
            .nowhere => unreachable, // verifier: uses follow defs
            .slot => {
                const physical = try self.allocScratch(register, locked);
                try self.loadSlot(physical, self.slotOf(register));
                self.location[register] = .{ .register = physical };
                return physical;
            },
            .immediate => |value| {
                const physical = try self.allocScratch(register, locked);
                try self.materialize(physical, @bitCast(value));
                self.location[register] = .{ .register = physical };
                return physical;
            },
            .table => |offset| {
                const physical = try self.allocScratch(register, locked);
                try self.loadTable(physical, offset);
                self.location[register] = .{ .register = physical };
                return physical;
            },
            .alias => |lazy| {
                if (self.local_version[lazy.local] == lazy.version) {
                    if (self.pinned[lazy.local]) |physical| return physical;
                }
                const physical = try self.allocScratch(register, locked);
                if (self.local_version[lazy.local] == lazy.version) {
                    try self.loadSlot(physical, lazy.local);
                } else {
                    try self.loadSlot(physical, self.slotOf(register));
                }
                self.location[register] = .{ .register = physical };
                return physical;
            },
        }
    }

    fn operandFloat(self: *Emitter, register: ir.Register, locked: []const u5) error{OutOfMemory}!u5 {
        switch (self.location[register]) {
            .fregister => |physical| return physical,
            .register, .immediate => unreachable,
            .nowhere => unreachable,
            .slot => {
                const physical = try self.allocFloat(register, locked);
                try self.floadSlot(physical, self.slotOf(register));
                self.location[register] = .{ .fregister = physical };
                return physical;
            },
            .table => |offset| {
                const physical = try self.allocFloat(register, locked);
                try self.floadTable(physical, offset);
                self.location[register] = .{ .fregister = physical };
                return physical;
            },
            .alias => |lazy| {
                if (self.local_version[lazy.local] == lazy.version) {
                    if (self.pinned[lazy.local]) |physical| return physical;
                }
                const physical = try self.allocFloat(register, locked);
                if (self.local_version[lazy.local] == lazy.version) {
                    try self.floadSlot(physical, lazy.local);
                } else {
                    try self.floadSlot(physical, self.slotOf(register));
                }
                self.location[register] = .{ .fregister = physical };
                return physical;
            },
        }
    }

    /// Fetch a value into a specific register of its class (ABI
    /// marshaling) — never touches pool ownership.
    fn fetchInto(self: *Emitter, target: u5, register: ir.Register) error{OutOfMemory}!void {
        if (self.isFloat(register)) return self.ffetchInto(target, register);
        switch (self.location[register]) {
            .register => |physical| try self.movReg(target, physical),
            .fregister => unreachable,
            .nowhere => unreachable,
            .slot => try self.loadSlot(target, self.slotOf(register)),
            .immediate => |value| try self.materialize(target, @bitCast(value)),
            .table => |offset| try self.loadTable(target, offset),
            .alias => |lazy| {
                if (self.local_version[lazy.local] == lazy.version) {
                    if (self.pinned[lazy.local]) |physical| {
                        try self.movReg(target, physical);
                    } else {
                        try self.loadSlot(target, lazy.local);
                    }
                } else {
                    try self.loadSlot(target, self.slotOf(register));
                }
            },
        }
    }

    fn ffetchInto(self: *Emitter, target: u5, register: ir.Register) error{OutOfMemory}!void {
        switch (self.location[register]) {
            .fregister => |physical| try self.fmovRegs(target, physical),
            .register, .immediate => unreachable,
            .nowhere => unreachable,
            .slot => try self.floadSlot(target, self.slotOf(register)),
            .table => |offset| try self.floadTable(target, offset),
            .alias => |lazy| {
                if (self.local_version[lazy.local] == lazy.version) {
                    if (self.pinned[lazy.local]) |physical| {
                        try self.fmovRegs(target, physical);
                    } else {
                        try self.floadSlot(target, lazy.local);
                    }
                } else {
                    try self.floadSlot(target, self.slotOf(register));
                }
            },
        }
    }

    /// Before a local is overwritten: any live lazy alias to it gets
    /// its own copy of the current value.
    fn materializeAliases(self: *Emitter, local: u32) error{OutOfMemory}!void {
        const version = self.local_version[local];
        const floaty = self.function.locals[local].local_type == .float;
        for (self.location, 0..) |current, register| {
            if (current != .alias) continue;
            if (current.alias.local != local or current.alias.version != version) continue;
            if (self.last_use[register] <= self.position) continue;
            if (self.pinned[local]) |physical| {
                if (floaty) {
                    try self.fstoreSlot(physical, self.slotOf(@intCast(register)));
                } else {
                    try self.storeSlot(physical, self.slotOf(@intCast(register)));
                }
            } else if (floaty) {
                try self.floadSlot(fhelper, local);
                try self.fstoreSlot(fhelper, self.slotOf(@intCast(register)));
            } else {
                try self.loadSlot(helper, local);
                try self.storeSlot(helper, self.slotOf(@intCast(register)));
            }
            self.location[register] = .slot;
        }
    }

    /// Before a call: value-pool registers do not survive the C ABI,
    /// so every live one spills to its slot.  The float pool is
    /// callee-saved (d12-d15) and rides through.
    fn spillForCall(self: *Emitter) error{OutOfMemory}!void {
        for (scratch_pool, 0..) |physical, index| {
            const resident = self.scratch_owner[index] orelse continue;
            if (self.last_use[resident] > self.position) {
                try self.storeSlot(physical, self.slotOf(resident));
                self.location[resident] = .slot;
            } else {
                self.location[resident] = .nowhere;
            }
            self.scratch_owner[index] = null;
        }
    }

    /// A destination register for `item` in its class, preferring to
    /// reuse a dying operand's pool register.
    fn destRegister(self: *Emitter, item: ir.Register, operands: []const ir.Register, locked: []const u5) error{OutOfMemory}!u5 {
        if (self.isFloat(item)) return self.destFloat(item, operands, locked);
        for (operands) |operand| {
            if (self.last_use[operand] > self.position) continue;
            switch (self.location[operand]) {
                .register => |physical| {
                    self.scratch_owner[poolIndexOf(physical)] = item;
                    self.location[operand] = .nowhere;
                    self.location[item] = .{ .register = physical };
                    return physical;
                },
                else => {},
            }
        }
        const physical = try self.allocScratch(item, locked);
        self.location[item] = .{ .register = physical };
        return physical;
    }

    fn destFloat(self: *Emitter, item: ir.Register, operands: []const ir.Register, locked: []const u5) error{OutOfMemory}!u5 {
        for (operands) |operand| {
            if (self.last_use[operand] > self.position) continue;
            switch (self.location[operand]) {
                .fregister => |physical| {
                    self.float_owner[floatPoolIndexOf(physical)] = item;
                    self.location[operand] = .nowhere;
                    self.location[item] = .{ .fregister = physical };
                    return physical;
                },
                else => {},
            }
        }
        const physical = try self.allocFloat(item, locked);
        self.location[item] = .{ .fregister = physical };
        return physical;
    }

    /// When `item`'s only use is the adjacent local_set of a pinned
    /// local of the same class, the producer writes the pinned
    /// register directly — no temporary, no mov.
    fn absorbTarget(self: *Emitter, item: ir.Register, following: ?ir.Register) error{OutOfMemory}!?u5 {
        const next = following orelse return null;
        if (self.use_count[item] != 1) return null;
        switch (self.function.instructions[next]) {
            .local_set => |set| {
                if (set.value != item) return null;
                const physical = self.pinned[set.local] orelse return null;
                const local_floaty = self.function.locals[set.local].local_type == .float;
                if (local_floaty != self.isFloat(item)) return null;
                try self.materializeAliases(set.local);
                self.pending_absorb = set.local;
                self.location[item] = .nowhere;
                return physical;
            },
            else => return null,
        }
    }

    /// The destination for a producing instruction: the pinned local
    /// register when the adjacent local_set absorbs it, a pool
    /// register otherwise.
    fn resultRegister(
        self: *Emitter,
        item: ir.Register,
        following: ?ir.Register,
        operands: []const ir.Register,
        locked: []const u5,
    ) error{OutOfMemory}!u5 {
        if (try self.absorbTarget(item, following)) |physical| return physical;
        return self.destRegister(item, operands, locked);
    }

    // -- the function ------------------------------------------------------

    fn emitFunction(self: *Emitter) native.RunError!void {
        const function = self.function;
        try self.analyze();
        const slots = function.locals.len + function.instructions.len;
        self.frame_size = std.mem.alignForward(u64, @as(u64, slots) * 8, 16);
        self.epilogue = try self.newMark();
        self.propagate = try self.newMark();
        const block_marks = try self.arena.alloc(u32, function.blocks.len);
        for (block_marks) |*mark| mark.* = try self.newMark();
        self.block_marks = block_marks;
        self.pinned = try self.arena.alloc(?u5, function.locals.len);
        self.local_version = try self.arena.alloc(u32, function.locals.len);
        @memset(self.local_version, 0);
        var next_pinned: usize = 0;
        var next_float_pinned: usize = 0;
        for (self.pinned, function.locals) |*slot, local| {
            if (local.local_type == .float) {
                slot.* = if (next_float_pinned < float_pinned_pool.len) blk: {
                    defer next_float_pinned += 1;
                    break :blk float_pinned_pool[next_float_pinned];
                } else null;
            } else {
                slot.* = if (next_pinned < pinned_pool.len) blk: {
                    defer next_pinned += 1;
                    break :blk pinned_pool[next_pinned];
                } else null;
            }
        }

        // Check the depth budget before touching SP.  A failed call
        // must be able to report call_depth_exceeded even when the
        // native stack has no room for this function's full frame.
        // x0 is still the State pointer and x13 is caller-saved, so
        // this path changes no register the caller expects preserved.
        const depth_ok = try self.newMark();
        try self.loadWord(helper, 0, abi.depth_offset);
        try self.word(0xF10005AD); // subs x13, x13, #1
        try self.storeWord(helper, 0, abi.depth_offset);
        try self.branchCond(ge, depth_ok);
        try self.materialize(helper, @bitCast(abi.trap(.call_depth_exceeded)));
        try self.storeWord(helper, 0, abi.trap_offset);
        try self.materialize(helper, self.function_index);
        try self.storeWord(helper, 0, abi.trap_function_offset);
        try self.materialize(helper, 0);
        try self.storeWord(helper, 0, abi.trap_instruction_offset);
        switch (function.return_type) {
            .none => {},
            .float => try self.fmovFromValue(0, zr),
            else => try self.movReg(0, zr),
        }
        try self.word(0xD65F03C0); // ret
        self.bind(depth_ok);

        // Prologue: saves (x19-x28 always; d8-d15 when floats are in
        // play), links the Darwin-compatible frame record, allocates
        // the frame, then homes State, the serial, parameters, and
        // typed zeros.
        try self.word(0xA9BF7BFD); // stp x29, x30, [sp, #-16]!
        try self.word(0x910003FD); // mov x29, sp
        try self.word(0xA9BF53F3); // stp x19, x20, [sp, #-16]!
        try self.word(0xA9BF5BF5); // stp x21, x22, [sp, #-16]!
        try self.word(0xA9BF63F7); // stp x23, x24, [sp, #-16]!
        try self.word(0xA9BF6BF9); // stp x25, x26, [sp, #-16]!
        try self.word(0xA9BF73FB); // stp x27, x28, [sp, #-16]!
        if (self.uses_floats) {
            try self.word(0x6DBF27E8); // stp d8, d9, [sp, #-16]!
            try self.word(0x6DBF2FEA); // stp d10, d11, [sp, #-16]!
            try self.word(0x6DBF37EC); // stp d12, d13, [sp, #-16]!
            try self.word(0x6DBF3FEE); // stp d14, d15, [sp, #-16]!
        }
        if (self.frame_size <= 4095) {
            try self.subImmediate(31, 31, @intCast(self.frame_size));
        } else {
            try self.materialize(helper, self.frame_size);
            try self.word(0xCB2D63FF); // sub sp, sp, x13 (extended)
        }
        try self.movReg(state, 0);

        // Parameters arrive per the C ABI — x1.. for values, d0.. for
        // floats — and move into their pinned homes or slots before
        // anything can clobber the argument registers.
        var value_argument: u5 = 1;
        var float_argument: u5 = 0;
        for (function.locals[0..function.parameter_count], 0..) |local, index| {
            const floaty = local.local_type == .float;
            const incoming = if (floaty) float_argument else value_argument;
            if (floaty) float_argument += 1 else value_argument += 1;
            if (self.pinned[index]) |physical| {
                if (floaty) {
                    try self.fmovRegs(physical, incoming);
                } else {
                    try self.movReg(physical, incoming);
                }
            } else if (floaty) {
                try self.fstoreSlot(incoming, index);
            } else {
                try self.storeSlot(incoming, index);
            }
        }

        // The frame serial (x28): bindings want a real one; every
        // other function passes zero, exactly as MIR emits.
        if (abi.wantsSerial(self.program, function)) {
            try self.movReg(0, state);
            try self.loadTable(16, abi.serviceOffset("svc_serial"));
            try self.callRegister(16);
            try self.movReg(serial, 0);
        } else {
            try self.movReg(serial, zr);
        }

        // Typed zeros for non-parameter locals (S40 late declarations).
        for (function.locals[function.parameter_count..], function.parameter_count..) |local, index| {
            const home = self.pinned[index];
            switch (local.local_type) {
                .float => {
                    if (home) |physical| {
                        try self.fmovFromValue(physical, zr);
                    } else {
                        try self.storeSlot(zr, index);
                    }
                },
                .string => {
                    const offset = AddressTable.constant(self.program.constants.len);
                    if (home) |physical| {
                        try self.loadTable(physical, offset);
                    } else {
                        try self.loadTable(helper2, offset);
                        try self.storeSlot(helper2, index);
                    }
                },
                .heap => |heap_index| {
                    // Null: a zero view for viewable arrays, the null
                    // handle for everything else.
                    const null_value: u64 = if (viewable(self.program, heap_index)) 0 else 0xFFFF_FFFF;
                    if (home) |physical| {
                        try self.materialize(physical, null_value);
                    } else {
                        try self.materialize(helper2, null_value);
                        try self.storeSlot(helper2, index);
                    }
                },
                .strukt => |struct_layout| {
                    try self.movReg(0, state);
                    try self.materialize(1, struct_layout);
                    try self.loadTable(16, abi.serviceOffset("svc_zero_strukt"));
                    try self.callRegister(16);
                    if (home) |physical| {
                        try self.movReg(physical, 0);
                    } else {
                        try self.storeSlot(0, index);
                    }
                    try self.trapCheck();
                },
                else => {
                    if (home) |physical| {
                        try self.movReg(physical, zr);
                    } else {
                        try self.storeSlot(zr, index);
                    }
                },
            }
        }

        for (function.blocks, 0..) |block, index| {
            self.bind(self.block_marks[index]);
            self.current_block = @intCast(index);
            // Temporaries never cross blocks (the IR guarantees it),
            // so the pools reset clean at every block edge.
            self.scratch_owner = @splat(null);
            self.float_owner = @splat(null);
            self.pending_compare = null;
            for (block.items, 0..) |item, at| {
                const following: ?ir.Register =
                    if (at + 1 < block.items.len) block.items[at + 1] else null;
                try self.emitInstruction(item, following);
                self.position += 1;
            }
        }

        // Trap stubs: record the triple, return the default.
        for (self.sites.items) |site| {
            self.bind(site.mark);
            try self.materialize(helper, @bitCast(abi.trap(site.code)));
            try self.storeWord(helper, state, abi.trap_offset);
            try self.materialize(helper, self.function_index);
            try self.storeWord(helper, state, abi.trap_function_offset);
            try self.materialize(helper, site.instruction);
            try self.storeWord(helper, state, abi.trap_instruction_offset);
            try self.branchTo(self.propagate);
        }
        self.bind(self.propagate);
        // The default return: zero of the return type; a trap
        // abandons the depth budget.
        switch (function.return_type) {
            .none => {},
            .float => try self.fmovFromValue(0, zr),
            else => try self.movReg(0, zr),
        }
        try self.branchTo(self.epilogue);
        self.bind(self.epilogue);
        if (self.frame_size <= 4095) {
            try self.addImmediate(31, 31, @intCast(self.frame_size));
        } else {
            try self.materialize(helper, self.frame_size);
            try self.word(0x8B2D63FF); // add sp, sp, x13 (extended)
        }
        if (self.uses_floats) {
            try self.word(0x6CC13FEE); // ldp d14, d15, [sp], #16
            try self.word(0x6CC137EC); // ldp d12, d13, [sp], #16
            try self.word(0x6CC12FEA); // ldp d10, d11, [sp], #16
            try self.word(0x6CC127E8); // ldp d8, d9, [sp], #16
        }
        try self.word(0xA8C173FB); // ldp x27, x28, [sp], #16
        try self.word(0xA8C16BF9); // ldp x25, x26, [sp], #16
        try self.word(0xA8C163F7); // ldp x23, x24, [sp], #16
        try self.word(0xA8C15BF5); // ldp x21, x22, [sp], #16
        try self.word(0xA8C153F3); // ldp x19, x20, [sp], #16
        try self.word(0xA8C17BFD); // ldp x29, x30, [sp], #16
        try self.word(0xD65F03C0); // ret

        try self.patch();
    }

    fn patch(self: *Emitter) error{NativeFailed}!void {
        for (self.fixups.items) |fixup| {
            const target = self.marks.items[fixup.mark] orelse return error.NativeFailed;
            const displacement: i64 = @intCast(@as(i64, @intCast(target)) - @as(i64, @intCast(fixup.at)));
            const instructions: i64 = @divExact(displacement, 4);
            if (!fixupFits(fixup.kind, instructions)) return error.NativeFailed;
            const bytes = self.code.items[fixup.at..][0..4];
            var encoded = std.mem.readInt(u32, bytes, .little);
            switch (fixup.kind) {
                .jump26 => encoded |= @as(u32, @intCast(instructions & 0x3FFFFFF)),
                .cond19 => encoded |= @as(u32, @intCast(instructions & 0x7FFFF)) << 5,
            }
            std.mem.writeInt(u32, bytes, encoded, .little);
        }
    }

    fn fixupFits(kind: FixupKind, instructions: i64) bool {
        const limit: i64 = switch (kind) {
            .jump26 => 1 << 25,
            .cond19 => 1 << 18,
        };
        return instructions >= -limit and instructions < limit;
    }

    fn emitInstruction(self: *Emitter, item: ir.Register, following: ?ir.Register) error{OutOfMemory}!void {
        const function = self.function;
        switch (function.instructions[item]) {
            // Constants and local reads stay lazy; a use forces them.
            .const_int => |value| self.location[item] = .{ .immediate = value },
            .const_boolean => |value| self.location[item] = .{ .immediate = @intFromBool(value) },
            .const_float => |value| self.location[item] = .{ .table = self.table.floatOffset(value) },
            .const_data => |data| self.location[item] = .{ .table = AddressTable.constant(data.constant) },
            .local_get => |local| self.location[item] = .{
                .alias = .{ .local = local, .version = self.local_version[local] },
            },
            .local_set => |set| {
                if (self.pending_absorb) |local| {
                    if (local == set.local) {
                        // The producer already wrote the pinned
                        // register; only the version turns over.
                        self.pending_absorb = null;
                        self.local_version[set.local] += 1;
                        return;
                    }
                }
                try self.materializeAliases(set.local);
                const floaty = function.locals[set.local].local_type == .float;
                if (self.pinned[set.local]) |physical| {
                    try self.fetchInto(physical, set.value);
                } else if (floaty) {
                    try self.ffetchInto(fhelper, set.value);
                    try self.fstoreSlot(fhelper, set.local);
                } else {
                    try self.fetchInto(helper, set.value);
                    try self.storeSlot(helper, set.local);
                }
                self.local_version[set.local] += 1;
                self.freeDead(&.{set.value});
            },
            // Blocks are laid out in index order, so a branch to the
            // physically next block is a fallthrough (aarch64
            // condition codes invert by flipping the low bit).
            .jump => |target| if (target != self.current_block + 1) {
                try self.branchTo(self.block_marks[target]);
            },
            .branch => |branching| {
                const fallthrough_then = branching.then_block == self.current_block + 1;
                const fallthrough_else = branching.else_block == self.current_block + 1;
                if (self.pending_compare) |pending| {
                    if (pending.register == branching.condition) {
                        self.pending_compare = null;
                        if (fallthrough_then) {
                            try self.branchCond(pending.condition ^ 1, self.block_marks[branching.else_block]);
                        } else {
                            try self.branchCond(pending.condition, self.block_marks[branching.then_block]);
                            if (!fallthrough_else) {
                                try self.branchTo(self.block_marks[branching.else_block]);
                            }
                        }
                        return;
                    }
                }
                const condition = try self.operandRegister(branching.condition, &.{});
                self.freeDead(&.{branching.condition});
                if (fallthrough_then) {
                    try self.branchZero(condition, self.block_marks[branching.else_block], true);
                } else {
                    try self.branchZero(condition, self.block_marks[branching.then_block], false);
                    if (!fallthrough_else) {
                        try self.branchTo(self.block_marks[branching.else_block]);
                    }
                }
            },
            .ret => |value| {
                // Return-value ownership first (S16): what the frame
                // still owned in the value goes loose for the caller,
                // through the marshaling slot the service reads.
                if (value) |register| {
                    if (abi.objectCarrying(self.program, function.return_type)) {
                        try self.fetchInto(helper2, register);
                        try self.storeWord(helper2, state, abi.slots_offset);
                        try self.spillForCall();
                        try self.movReg(0, state);
                        try self.materialize(1, self.function_index);
                        try self.movReg(2, serial);
                        try self.loadTable(16, abi.serviceOffset("svc_loosen"));
                        try self.callRegister(16);
                        // Success restores the depth budget.
                        try self.loadWord(helper, state, abi.depth_offset);
                        try self.addImmediate(helper, helper, 1);
                        try self.storeWord(helper, state, abi.depth_offset);
                        try self.loadWord(0, state, abi.slots_offset);
                        try self.branchTo(self.epilogue);
                        return;
                    }
                }
                try self.loadWord(helper, state, abi.depth_offset);
                try self.addImmediate(helper, helper, 1);
                try self.storeWord(helper, state, abi.depth_offset);
                if (value) |register| {
                    if (self.isFloat(register)) {
                        try self.ffetchInto(0, register);
                    } else {
                        try self.fetchInto(0, register);
                    }
                    self.freeDead(&.{register});
                }
                try self.branchTo(self.epilogue);
            },
            .trap => |code| try self.branchTo(try self.trapSite(code, item)),
            .call => |call| try self.emitCall(item, call, following),
            .unary => |operation| {
                if (function.result_types[item] == .float and operation.op == .negate) {
                    const operand = try self.operandFloat(operation.operand, &.{});
                    const dest = try self.resultRegister(item, following, &.{operation.operand}, &.{operand});
                    try self.word(0x1E614000 | @as(u32, operand) << 5 | dest); // fneg
                    self.freeDead(&.{operation.operand});
                    return;
                }
                const operand = try self.operandRegister(operation.operand, &.{});
                switch (operation.op) {
                    .negate => {
                        const overflow = try self.trapSite(.integer_overflow, item);
                        const dest = try self.resultRegister(item, following, &.{operation.operand}, &.{operand});
                        // subs dest, xzr, operand
                        try self.word(0xEB000000 | @as(u32, operand) << 16 | @as(u32, zr) << 5 | dest);
                        try self.branchCond(vs, overflow);
                    },
                    .logic_not => {
                        try self.compareImmediate(operand, 0);
                        const dest = try self.resultRegister(item, following, &.{operation.operand}, &.{operand});
                        try self.setCond(dest, eq);
                    },
                }
                self.freeDead(&.{operation.operand});
            },
            .convert => |operation| switch (operation.kind) {
                .int_to_float => {
                    const operand = try self.operandRegister(operation.operand, &.{});
                    const dest = try self.resultRegister(item, following, &.{operation.operand}, &.{});
                    try self.word(0x9E620000 | @as(u32, operand) << 5 | dest); // scvtf
                    self.freeDead(&.{operation.operand});
                },
                .float_to_int => {
                    // NaN, below -2^63, or at/above 2^63 traps;
                    // in-range truncates toward zero exactly like the
                    // interpreter (fcmp with itself raises V on NaN).
                    const range = try self.trapSite(.conversion_range, item);
                    const operand = try self.operandFloat(operation.operand, &.{});
                    try self.fcompare(operand, operand);
                    try self.branchCond(vs, range);
                    try self.floadTable(fhelper, self.table.floatOffset(-9223372036854775808.0));
                    try self.fcompare(operand, fhelper);
                    try self.branchCond(mi, range);
                    try self.floadTable(fhelper, self.table.floatOffset(9223372036854775808.0));
                    try self.fcompare(operand, fhelper);
                    try self.branchCond(ge, range);
                    const dest = try self.resultRegister(item, following, &.{operation.operand}, &.{});
                    try self.word(0x9E780000 | @as(u32, operand) << 5 | dest); // fcvtzs
                    self.freeDead(&.{operation.operand});
                },
            },
            .binary => |operation| try self.emitBinary(item, operation, following),
            .intrinsic => |call| try self.emitIntrinsic(item, call, following),
            .struct_make, .struct_get, .struct_set, .heap_new, .object_bind, .object_unbind => {
                try self.emitGeneric(item, following);
            },
            else => unreachable, // supported() refused everything else
        }
    }

    // -- calls and services ------------------------------------------------

    /// A Luce-to-Luce call: target from the function table, arguments
    /// per the C ABI in declaration order, trap check after.
    fn emitCall(self: *Emitter, item: ir.Register, call: anytype, following: ?ir.Register) error{OutOfMemory}!void {
        _ = following;
        const callee = &self.program.functions[call.function];
        var value_argument: u5 = 1;
        var float_argument: u5 = 0;
        for (call.arguments, 0..) |argument, index| {
            const floaty = callee.locals[index].local_type == .float;
            if (floaty) {
                try self.ffetchInto(float_argument, argument);
                float_argument += 1;
            } else {
                try self.fetchInto(value_argument, argument);
                value_argument += 1;
            }
        }
        self.freeDead(call.arguments);
        try self.spillForCall();
        try self.movReg(0, state);
        try self.loadTable(16, self.table.function(call.function));
        try self.callRegister(16);
        if (callee.return_type != .none) {
            if (callee.return_type == .float) {
                const dest = try self.destFloat(item, &.{}, &.{});
                try self.fmovRegs(dest, 0);
            } else {
                const dest = try self.destRegister(item, &.{}, &.{});
                try self.movReg(dest, 0);
            }
        }
        try self.trapCheck();
    }

    /// The generic service protocol, mirroring the MIR lowering:
    /// operands into the State's marshaling slots by type, then
    /// svc_instr_{i,d,v}(state, function, instruction, serial), the
    /// result register chosen by the instruction's result type.
    fn emitGeneric(self: *Emitter, item: ir.Register, following: ?ir.Register) error{OutOfMemory}!void {
        _ = following;
        var buffer: [2]ir.Register = undefined;
        const operands = operandsOf(&self.function.instructions[item], &buffer);
        for (operands, 0..) |operand, slot| {
            const offset = abi.slots_offset + 8 * @as(u64, slot);
            if (self.isFloat(operand)) {
                try self.ffetchInto(fhelper, operand);
                try self.fstoreWord(fhelper, state, offset);
            } else {
                try self.fetchInto(helper2, operand);
                try self.storeWord(helper2, state, offset);
            }
        }
        self.freeDead(operands);
        try self.spillForCall();
        try self.movReg(0, state);
        try self.materialize(1, self.function_index);
        try self.materialize(2, item);
        try self.movReg(3, serial);
        switch (self.typeOf(item)) {
            .none => {
                try self.loadTable(16, abi.serviceOffset("svc_instr_v"));
                try self.callRegister(16);
            },
            .float => {
                try self.loadTable(16, abi.serviceOffset("svc_instr_d"));
                try self.callRegister(16);
                const dest = try self.destFloat(item, &.{}, &.{});
                try self.fmovRegs(dest, 0);
            },
            else => {
                try self.loadTable(16, abi.serviceOffset("svc_instr_i"));
                try self.callRegister(16);
                const dest = try self.destRegister(item, &.{}, &.{});
                try self.movReg(dest, 0);
            },
        }
        try self.trapCheck();
    }

    /// A fast service call: arguments fetched straight into ABI
    /// registers (they never collide with the pools), result in
    /// x0/d0, trap check after.  `arguments` pairs ABI slots with IR
    /// registers; a null IR register means the literal goes in
    /// directly.
    const ServiceArgument = union(enum) {
        register: ir.Register,
        literal: u64,
        state_pointer,
        serial_word,
    };

    fn emitService(
        self: *Emitter,
        item: ir.Register,
        service: []const u8,
        arguments: []const ServiceArgument,
        free: []const ir.Register,
        result: enum { none, value, float },
        check: bool,
    ) error{OutOfMemory}!void {
        var value_slot: u5 = 0;
        var float_slot: u5 = 0;
        for (arguments) |argument| {
            switch (argument) {
                .state_pointer => {
                    try self.movReg(value_slot, state);
                    value_slot += 1;
                },
                .serial_word => {
                    try self.movReg(value_slot, serial);
                    value_slot += 1;
                },
                .literal => |value| {
                    try self.materialize(value_slot, value);
                    value_slot += 1;
                },
                .register => |register| {
                    if (self.isFloat(register)) {
                        try self.ffetchInto(float_slot, register);
                        float_slot += 1;
                    } else {
                        try self.fetchInto(value_slot, register);
                        value_slot += 1;
                    }
                },
            }
        }
        self.freeDead(free);
        try self.spillForCall();
        try self.loadTable(16, abi.serviceOffset(service));
        try self.callRegister(16);
        switch (result) {
            .none => {},
            .value => {
                const dest = try self.destRegister(item, &.{}, &.{});
                try self.movReg(dest, 0);
            },
            .float => {
                const dest = try self.destFloat(item, &.{}, &.{});
                try self.fmovRegs(dest, 0);
            },
        }
        if (check) try self.trapCheck();
    }

    // -- inline access (milestone 3's unboxed reads, transferred) ----------

    /// Null and liveness checks on a view register: the same traps
    /// the interpreter's resolve raises, inline.
    fn emitViewPrelude(self: *Emitter, item: ir.Register, view: u5) error{OutOfMemory}!void {
        const null_stub = try self.trapSite(.null_object, item);
        const dead_stub = try self.trapSite(.use_after_free, item);
        try self.branchZero(view, null_stub, true);
        try self.loadWord(helper, view, 16);
        try self.loadByte(helper, helper, 0);
        try self.branchZero(helper, dead_stub, true);
    }

    /// helper = helper + index * element_stride — one shifted add
    /// when the stride is a power of two (it is: RuntimeValue is a
    /// power-of-two-sized union), the generic multiply otherwise.
    fn emitElementAddress(self: *Emitter, index: u5) error{OutOfMemory}!void {
        const stride = abi.element_stride;
        if (std.math.isPowerOfTwo(stride)) {
            const shift: u6 = @intCast(std.math.log2_int(u64, stride));
            // add helper, helper, index, lsl #shift
            try self.word(0x8B000000 | @as(u32, index) << 16 |
                @as(u32, shift) << 10 | @as(u32, helper) << 5 | helper);
        } else if (stride == 24) {
            // stride 24: index*3 by one shifted add, then *8 into the
            // base — two adds, no multiply, no constant.
            // add helper2, index, index, lsl #1   (helper2 = 3*index)
            try self.word(0x8B000400 | @as(u32, index) << 16 | @as(u32, index) << 5 | helper2);
            // add helper, helper, helper2, lsl #3
            try self.word(0x8B000C00 | @as(u32, helper2) << 16 | @as(u32, helper) << 5 | helper);
        } else {
            try self.materialize(helper2, stride);
            try self.word(0x9B000000 | @as(u32, helper2) << 16 | @as(u32, helper) << 10 |
                @as(u32, index) << 5 | helper);
        }
    }

    /// Inline rank-1 array indexing: bounds check against the view,
    /// then a typed load or store at elements + index * stride +
    /// payload offset.
    fn emitArrayAccess(
        self: *Emitter,
        item: ir.Register,
        call: ir.Instruction.IntrinsicCall,
        element: types.Type,
        following: ?ir.Register,
    ) error{OutOfMemory}!void {
        const payloads = abi.payloadOffsets();
        const view = try self.operandRegister(call.arguments[0], &.{});
        const index = try self.operandRegister(call.arguments[1], &.{view});
        try self.emitViewPrelude(item, view);
        const bounds = try self.trapSite(.index_bounds, item);
        try self.loadWord(helper, view, 8);
        // Unsigned compare: a negative index reads as huge.
        try self.word(0xEB00001F | @as(u32, helper) << 16 | @as(u32, index) << 5); // cmp index, helper
        try self.branchCond(hs, bounds);
        // The destination (or store value) settles before the element
        // address lives in the helper — resultRegister's absorption
        // path may borrow the helper for alias copies.
        if (call.kind == .index_get) {
            const dest = switch (element) {
                .float => try self.resultRegister(item, following, &.{ call.arguments[0], call.arguments[1] }, &.{}),
                else => try self.resultRegister(item, following, &.{ call.arguments[0], call.arguments[1] }, &.{ view, index }),
            };
            try self.loadWord(helper, view, 0);
            try self.emitElementAddress(index);
            switch (element) {
                .float => try self.floadWord(dest, helper, payloads.float),
                .int => try self.loadWord(dest, helper, payloads.int),
                .boolean => try self.loadByte(dest, helper, payloads.boolean),
                else => unreachable,
            }
            self.freeDead(&.{ call.arguments[0], call.arguments[1] });
        } else {
            const value = call.arguments[2];
            const from = if (element == .float)
                try self.operandFloat(value, &.{})
            else
                try self.operandRegister(value, &.{ view, index });
            try self.loadWord(helper, view, 0);
            try self.emitElementAddress(index);
            switch (element) {
                .float => try self.fstoreWord(from, helper, payloads.float),
                .int => try self.storeWord(from, helper, payloads.int),
                .boolean => try self.storeByte(from, helper, payloads.boolean),
                else => unreachable,
            }
            self.freeDead(&.{ call.arguments[0], call.arguments[1], value });
        }
    }

    // -- binaries ----------------------------------------------------------

    fn immediateOperand(self: *const Emitter, register: ir.Register) ?i64 {
        return switch (self.location[register]) {
            .immediate => |value| value,
            else => null,
        };
    }

    fn conditionOf(op: ir.BinaryOp, float: bool) u4 {
        if (float) {
            // IEEE comparisons: false on NaN for everything but !=,
            // which these condition codes encode exactly (unordered
            // sets C and V; MI/LS/GT/GE/EQ all read false there).
            return switch (op) {
                .equal => eq,
                .not_equal => ne,
                .less => mi,
                .less_equal => ls,
                .greater => gt,
                .greater_equal => ge,
                else => unreachable,
            };
        }
        return switch (op) {
            .equal => eq,
            .not_equal => ne,
            .less => lt,
            .less_equal => le,
            .greater => gt,
            .greater_equal => ge,
            else => unreachable,
        };
    }

    /// The condition with operands swapped (a < b == b > a).
    fn swappedCondition(condition: u4) u4 {
        return switch (condition) {
            eq, ne => condition,
            lt => gt,
            gt => lt,
            le => ge,
            ge => le,
            else => unreachable,
        };
    }

    fn fitsImmediate(value: i64) bool {
        return value > -4096 and value < 4096;
    }

    fn emitBinary(self: *Emitter, item: ir.Register, operation: anytype, following: ?ir.Register) error{OutOfMemory}!void {
        switch (operation.operand_type) {
            // String concatenation has a direct service; string
            // ordering and struct equality live in the reference
            // implementation, like MIR's lowering.
            .string => {
                if (operation.op == .add) {
                    try self.emitService(item, "svc_str_concat", &.{
                        .state_pointer,
                        .{ .register = operation.left },
                        .{ .register = operation.right },
                    }, &.{ operation.left, operation.right }, .value, true);
                    return;
                }
                return self.emitGeneric(item, following);
            },
            .strukt => return self.emitGeneric(item, following),
            .float => return self.emitFloatBinary(item, operation, following),
            else => {},
        }
        if (operation.op.isComparison()) {
            // Heap handles and booleans compare as their words, like
            // Int — reference equality for objects.
            var condition = conditionOf(operation.op, false);
            if (self.immediateOperand(operation.right)) |value| blk: {
                if (!fitsImmediate(value)) break :blk;
                const left = try self.operandRegister(operation.left, &.{});
                try self.compareImmediate(left, value);
                self.freeDead(&.{ operation.left, operation.right });
                return self.finishComparison(item, condition, following);
            }
            if (self.immediateOperand(operation.left)) |value| blk: {
                if (!fitsImmediate(value)) break :blk;
                const right = try self.operandRegister(operation.right, &.{});
                try self.compareImmediate(right, value);
                condition = swappedCondition(condition);
                self.freeDead(&.{ operation.left, operation.right });
                return self.finishComparison(item, condition, following);
            }
            const left = try self.operandRegister(operation.left, &.{});
            const right = try self.operandRegister(operation.right, &.{left});
            try self.compareRegisters(left, right);
            self.freeDead(&.{ operation.left, operation.right });
            return self.finishComparison(item, condition, following);
        }
        switch (operation.op) {
            .add, .subtract => {
                const overflow = try self.trapSite(.integer_overflow, item);
                // adds/subs with a small immediate (negated flips the
                // op — flags still describe the true operation).
                if (self.immediateOperand(operation.right)) |value| blk: {
                    if (!fitsImmediate(value)) break :blk;
                    const effective_add = (operation.op == .add) == (value >= 0);
                    const magnitude: u12 = @intCast(@abs(value));
                    const left = try self.operandRegister(operation.left, &.{});
                    const dest = try self.resultRegister(item, following, &.{ operation.left, operation.right }, &.{left});
                    const base: u32 = if (effective_add) 0xB1000000 else 0xF1000000;
                    try self.word(base | @as(u32, magnitude) << 10 | @as(u32, left) << 5 | dest);
                    try self.branchCond(vs, overflow);
                    self.freeDead(&.{ operation.left, operation.right });
                    return;
                }
                const left = try self.operandRegister(operation.left, &.{});
                const right = try self.operandRegister(operation.right, &.{left});
                const dest = try self.resultRegister(item, following, &.{ operation.left, operation.right }, &.{ left, right });
                const base: u32 = if (operation.op == .add) 0xAB000000 else 0xEB000000;
                try self.word(base | @as(u32, right) << 16 | @as(u32, left) << 5 | dest);
                try self.branchCond(vs, overflow);
                self.freeDead(&.{ operation.left, operation.right });
            },
            .multiply => {
                const overflow = try self.trapSite(.integer_overflow, item);
                const left = try self.operandRegister(operation.left, &.{});
                const right = try self.operandRegister(operation.right, &.{left});
                // smulh first into the helper so the destination may
                // alias an operand.
                try self.word(0x9B407C00 | @as(u32, right) << 16 | @as(u32, left) << 5 | helper2);
                const dest = try self.resultRegister(item, following, &.{ operation.left, operation.right }, &.{ left, right });
                try self.word(0x9B007C00 | @as(u32, right) << 16 | @as(u32, left) << 5 | dest);
                // Overflow unless the high word is the sign extension
                // of the low: cmp helper2, dest, asr #63.
                try self.word(0xEB000000 | 0x2 << 22 | @as(u32, dest) << 16 |
                    @as(u32, 63) << 10 | @as(u32, helper2) << 5 | zr);
                try self.branchCond(ne, overflow);
                self.freeDead(&.{ operation.left, operation.right });
            },
            .divide, .remainder => {
                // The MIR lowering's exact guards — zero traps, MIN/-1
                // traps — with each guard elided when a constant
                // operand decides it statically (same semantics: the
                // elided branch could never fire).
                const divisor_constant = self.immediateOperand(operation.right);
                const dividend_constant = self.immediateOperand(operation.left);
                const left = try self.operandRegister(operation.left, &.{});
                const right = try self.operandRegister(operation.right, &.{left});
                if (divisor_constant) |value| {
                    if (value == 0) {
                        // Statically always a trap.
                        try self.branchTo(try self.trapSite(.divide_by_zero, item));
                    }
                } else {
                    try self.branchZero(right, try self.trapSite(.divide_by_zero, item), true);
                }
                const divisor_may_be_minus_one =
                    divisor_constant == null or divisor_constant.? == -1;
                const dividend_may_be_minimum =
                    dividend_constant == null or dividend_constant.? == std.math.minInt(i64);
                if (divisor_may_be_minus_one and dividend_may_be_minimum) {
                    const overflow = try self.trapSite(.integer_overflow, item);
                    const fine = try self.newMark();
                    if (divisor_constant == null) {
                        try self.compareImmediate(right, -1);
                        try self.branchCond(ne, fine);
                    }
                    try self.movz(helper2, 0x8000, 3); // i64 minimum
                    try self.compareRegisters(left, helper2);
                    try self.branchCond(eq, overflow);
                    self.bind(fine);
                }
                const dest = try self.resultRegister(item, following, &.{ operation.left, operation.right }, &.{ left, right });
                if (operation.op == .divide) {
                    // sdiv dest, left, right
                    try self.word(0x9AC00C00 | @as(u32, right) << 16 | @as(u32, left) << 5 | dest);
                } else {
                    try self.word(0x9AC00C00 | @as(u32, right) << 16 | @as(u32, left) << 5 | helper2);
                    // msub dest, helper2, right, left
                    try self.word(0x9B008000 | @as(u32, right) << 16 | @as(u32, left) << 10 |
                        @as(u32, helper2) << 5 | dest);
                }
                self.freeDead(&.{ operation.left, operation.right });
            },
            else => unreachable,
        }
    }

    fn emitFloatBinary(self: *Emitter, item: ir.Register, operation: anytype, following: ?ir.Register) error{OutOfMemory}!void {
        if (operation.op.isComparison()) {
            const left = try self.operandFloat(operation.left, &.{});
            const right = try self.operandFloat(operation.right, &.{left});
            try self.fcompare(left, right);
            self.freeDead(&.{ operation.left, operation.right });
            return self.finishComparison(item, conditionOf(operation.op, true), following);
        }
        if (operation.op == .remainder) {
            // Float remainder lives in the reference implementation,
            // like MIR's lowering.
            return self.emitGeneric(item, following);
        }
        const left = try self.operandFloat(operation.left, &.{});
        const right = try self.operandFloat(operation.right, &.{left});
        const dest = try self.resultRegister(item, following, &.{ operation.left, operation.right }, &.{ left, right });
        const base: u32 = switch (operation.op) {
            .add => 0x1E602800,
            .subtract => 0x1E603800,
            .multiply => 0x1E600800,
            .divide => 0x1E601800,
            else => unreachable,
        };
        try self.word(base | @as(u32, right) << 16 | @as(u32, left) << 5 | dest);
        self.freeDead(&.{ operation.left, operation.right });
    }

    /// A comparison's flags either fuse into the adjacent consuming
    /// branch or become a boolean via cset.
    fn finishComparison(self: *Emitter, item: ir.Register, condition: u4, following: ?ir.Register) error{OutOfMemory}!void {
        if (following) |next| {
            if (self.use_count[item] == 1) {
                switch (self.function.instructions[next]) {
                    .branch => |branching| if (branching.condition == item) {
                        self.pending_compare = .{ .register = item, .condition = condition };
                        return;
                    },
                    else => {},
                }
            }
        }
        const dest = try self.resultRegister(item, following, &.{}, &.{});
        try self.setCond(dest, condition);
    }

    // -- intrinsics ----------------------------------------------------------

    fn emitIntrinsic(self: *Emitter, item: ir.Register, call: ir.Instruction.IntrinsicCall, following: ?ir.Register) error{OutOfMemory}!void {
        const function = self.function;
        switch (call.kind) {
            .assert_true => {
                const failed = try self.trapSite(.assertion_failed, item);
                const value = try self.operandRegister(call.arguments[0], &.{});
                self.freeDead(&.{call.arguments[0]});
                try self.branchZero(value, failed, true);
            },
            .str_value => switch (function.result_types[call.arguments[0]]) {
                // str on a String is a move, exactly as MIR lowers
                // it.  Fetch before any dest bookkeeping.
                .string => {
                    const dest = try self.destRegister(item, &.{}, &.{});
                    try self.fetchInto(dest, call.arguments[0]);
                    self.freeDead(&.{call.arguments[0]});
                },
                .int => try self.emitService(item, "svc_str_int", &.{
                    .state_pointer,
                    .{ .register = call.arguments[0] },
                }, &.{call.arguments[0]}, .value, true),
                else => try self.emitGeneric(item, following),
            },
            .chr_code => try self.emitService(item, "svc_chr", &.{
                .state_pointer,
                .{ .literal = self.function_index },
                .{ .literal = item },
                .{ .register = call.arguments[0] },
            }, &.{call.arguments[0]}, .value, true),
            .string_find_byte => try self.emitService(item, "svc_str_find_byte", &.{
                .state_pointer,
                .{ .literal = self.function_index },
                .{ .literal = item },
                .{ .register = call.arguments[0] },
                .{ .register = call.arguments[1] },
                .{ .register = call.arguments[2] },
            }, call.arguments, .value, true),
            .append_ascii => try self.emitService(item, "svc_builder_append_ascii", &.{
                .state_pointer,
                .{ .literal = self.function_index },
                .{ .literal = item },
                .{ .register = call.arguments[0] },
                .{ .register = call.arguments[1] },
            }, call.arguments, .none, true),
            .string_slice => try self.emitService(item, "svc_str_slice", &.{
                .state_pointer,
                .{ .literal = self.function_index },
                .{ .literal = item },
                .{ .register = call.arguments[0] },
                .{ .register = call.arguments[1] },
                .{ .register = call.arguments[2] },
            }, call.arguments, .value, true),
            .string_byte => {
                // Inline: bounds against the descriptor, one byte
                // load (unsigned compare treats negatives as huge).
                const bounds = try self.trapSite(.string_bounds, item);
                const text = try self.operandRegister(call.arguments[0], &.{});
                const index = try self.operandRegister(call.arguments[1], &.{text});
                try self.loadWord(helper, text, 8);
                try self.word(0xEB00001F | @as(u32, helper) << 16 | @as(u32, index) << 5);
                try self.branchCond(hs, bounds);
                const dest = try self.resultRegister(item, following, &.{ call.arguments[0], call.arguments[1] }, &.{ text, index });
                try self.loadWord(helper, text, 0);
                // ldrb dest, [helper, index]
                try self.word(0x38606800 | @as(u32, index) << 16 | @as(u32, helper) << 5 | dest);
                self.freeDead(&.{ call.arguments[0], call.arguments[1] });
            },
            .len => {
                const operand = call.arguments[0];
                const of = function.result_types[operand];
                if (of == .string) {
                    // A string is a {ptr, len} descriptor: one load.
                    const text = try self.operandRegister(operand, &.{});
                    const dest = try self.resultRegister(item, following, &.{operand}, &.{text});
                    try self.loadWord(dest, text, 8);
                    self.freeDead(&.{operand});
                } else if (of == .heap and viewable(self.program, of.heap)) {
                    const view = try self.operandRegister(operand, &.{});
                    try self.emitViewPrelude(item, view);
                    const dest = try self.resultRegister(item, following, &.{operand}, &.{view});
                    try self.loadWord(dest, view, 8);
                    self.freeDead(&.{operand});
                } else {
                    try self.emitService(item, "svc_obj_len", &.{
                        .state_pointer,
                        .{ .literal = self.function_index },
                        .{ .literal = item },
                        .{ .register = operand },
                    }, &.{operand}, .value, true);
                }
            },
            .append_value => {
                const receiver = function.result_types[call.arguments[0]];
                const shape: ?types.HeapType = if (receiver == .heap)
                    self.program.heap_types[receiver.heap]
                else
                    null;
                if (shape != null and shape.? == .builder) {
                    try self.emitService(item, "svc_builder_append", &.{
                        .state_pointer,
                        .{ .literal = self.function_index },
                        .{ .literal = item },
                        .{ .register = call.arguments[0] },
                        .{ .register = call.arguments[1] },
                    }, call.arguments, .none, true);
                } else if (shape != null and shape.? == .list and switch (shape.?.list) {
                    .int, .boolean, .float, .string => true,
                    else => false,
                }) {
                    const service: []const u8 = switch (shape.?.list) {
                        .int => "svc_list_append_i",
                        .boolean => "svc_list_append_b",
                        .float => "svc_list_append_d",
                        .string => "svc_list_append_s",
                        else => unreachable,
                    };
                    try self.emitService(item, service, &.{
                        .state_pointer,
                        .{ .literal = self.function_index },
                        .{ .literal = item },
                        .{ .register = call.arguments[0] },
                        .{ .register = call.arguments[1] },
                    }, call.arguments, .none, true);
                } else {
                    try self.emitGeneric(item, following);
                }
            },
            .index_get, .index_set => {
                if (self.arrayInlineElement(call)) |element| {
                    try self.emitArrayAccess(item, call, element, following);
                } else if (self.fastSeqElement(call)) |element| {
                    const getter = call.kind == .index_get;
                    const service: []const u8 = if (getter)
                        (if (element == .float) "svc_seq_get_d" else "svc_seq_get_i")
                    else
                        (if (element == .float) "svc_seq_set_d" else "svc_seq_set_i");
                    var arguments: [6]ServiceArgument = undefined;
                    arguments[0] = .state_pointer;
                    arguments[1] = .{ .literal = self.function_index };
                    arguments[2] = .{ .literal = item };
                    arguments[3] = .{ .register = call.arguments[0] };
                    arguments[4] = .{ .register = call.arguments[1] };
                    var count: usize = 5;
                    if (!getter) {
                        arguments[5] = .{ .register = call.arguments[2] };
                        count = 6;
                    }
                    try self.emitService(item, service, arguments[0..count], call.arguments, if (!getter)
                        .none
                    else if (element == .float)
                        .float
                    else
                        .value, true);
                } else {
                    try self.emitGeneric(item, following);
                }
            },
            else => try self.emitGeneric(item, following),
        }
    }

    // -- gates shared with the MIR lowering's shape ------------------------

    fn viewable(program: *const ir.Program, heap_index: u32) bool {
        return switch (program.heap_types[heap_index]) {
            .array => |shape| switch (shape.element) {
                .int, .boolean, .float => true,
                else => false,
            },
            else => false,
        };
    }

    fn fastSeqElement(self: *const Emitter, call: ir.Instruction.IntrinsicCall) ?types.Type {
        const of = self.function.result_types[call.arguments[0]];
        if (of != .heap) return null;
        const wanted: usize = if (call.kind == .index_get) 2 else 3;
        if (call.arguments.len != wanted) return null;
        const element = switch (self.program.heap_types[of.heap]) {
            .list => |element| element,
            else => return null,
        };
        return switch (element) {
            .int, .boolean, .float => element,
            else => null,
        };
    }

    fn arrayInlineElement(self: *const Emitter, call: ir.Instruction.IntrinsicCall) ?types.Type {
        const of = self.function.result_types[call.arguments[0]];
        if (of != .heap) return null;
        const wanted: usize = if (call.kind == .index_get) 2 else 3;
        if (call.arguments.len != wanted) return null;
        return switch (self.program.heap_types[of.heap]) {
            .array => |shape| if (shape.rank == 1) switch (shape.element) {
                .int, .boolean, .float => shape.element,
                else => null,
            } else null,
            else => null,
        };
    }
};

// ---------------------------------------------------------------------------
// Tests — behavior is proven by native_spec's oracle, which runs
// every corpus program on this backend too; here the gate itself.
// ---------------------------------------------------------------------------

const compile_mod = @import("compile.zig");
const testing = std.testing;

fn emittedWord(bytes: []const u8, index: usize) u32 {
    return std.mem.readInt(u32, bytes[index * 4 ..][0..4], .little);
}

test "cached images are source-derived and backend-separated" {
    // Mirror the generator_identity fold: on x86-64 the emitter source
    // is codegen.zig ++ codegen_x86.zig, so the identity must too.
    const backend_source = if (on_x86)
        @embedFile("codegen.zig") ++ @embedFile("codegen_x86.zig")
    else
        @embedFile("codegen.zig");
    const source_identity = generatorIdentityFor(
        backend_source,
        builtin.zig_version_string,
    );
    try testing.expectEqual(generator_identity, source_identity);
    try testing.expectEqual(fingerprint(), fingerprint());
    try testing.expectEqual(imageTextHash("module"), imageTextHash("module"));
    try testing.expect(generator_identity != generatorIdentityFor("changed", builtin.zig_version_string));
    try testing.expect(generator_identity != generatorIdentityFor(@embedFile("codegen.zig"), "different-zig"));
    try testing.expect(fingerprint() != fingerprintFor(generator_identity ^ 1, native.fingerprint()));
    try testing.expect(fingerprint() != fingerprintFor(generator_identity, native.fingerprint() ^ 1));
    try testing.expect(imageTextHash("module-a") != imageTextHash("module-b"));

    // The shared .lci format is deliberately unable to confuse a MIR
    // payload with a self-written payload, even for the same module.
    const module_bytes = "same portable module";
    const zig_keys: image.Keys = .{
        .fingerprint = fingerprint(),
        .module_hash = image.hashModule(module_bytes),
        .text_hash = imageTextHash(module_bytes),
    };
    const mir_keys: image.Keys = .{
        .fingerprint = native.fingerprint(),
        .module_hash = image.hashModule(module_bytes),
        .text_hash = imageTextHash(module_bytes),
    };
    try testing.expect(zig_keys.fingerprint != mir_keys.fingerprint);

    const spans = [_][]const u8{"code"};
    const zig_bytes = try image.encode(testing.allocator, &spans, zig_keys);
    defer testing.allocator.free(zig_bytes);
    const mir_bytes = try image.encode(testing.allocator, &spans, mir_keys);
    defer testing.allocator.free(mir_bytes);
    try testing.expectError(error.WrongFingerprint, image.decode(testing.allocator, zig_bytes, mir_keys, 1));
    try testing.expectError(error.WrongFingerprint, image.decode(testing.allocator, mir_bytes, zig_keys, 1));
}

fn expectRejectedFixup(kind: FixupKind, target: usize) !void {
    var emitter: Emitter = .{
        .arena = testing.allocator,
        .program = undefined,
        .table = undefined,
        .function = undefined,
        .function_index = 0,
    };
    defer emitter.code.deinit(testing.allocator);
    defer emitter.marks.deinit(testing.allocator);
    defer emitter.fixups.deinit(testing.allocator);

    try emitter.word(switch (kind) {
        .jump26 => 0x14000000,
        .cond19 => 0x54000000,
    });
    const mark = try emitter.newMark();
    emitter.marks.items[mark] = target;
    try emitter.fixups.append(testing.allocator, .{ .at = 0, .mark = mark, .kind = kind });
    try testing.expectError(error.NativeFailed, emitter.patch());
}

test "branch fixups reject displacement truncation" {
    const cond_limit: i64 = 1 << 18;
    const jump_limit: i64 = 1 << 25;
    try testing.expect(Emitter.fixupFits(.cond19, -cond_limit));
    try testing.expect(Emitter.fixupFits(.cond19, cond_limit - 1));
    try testing.expect(!Emitter.fixupFits(.cond19, -cond_limit - 1));
    try testing.expect(!Emitter.fixupFits(.cond19, cond_limit));
    try testing.expect(Emitter.fixupFits(.jump26, -jump_limit));
    try testing.expect(Emitter.fixupFits(.jump26, jump_limit - 1));
    try testing.expect(!Emitter.fixupFits(.jump26, -jump_limit - 1));
    try testing.expect(!Emitter.fixupFits(.jump26, jump_limit));

    try expectRejectedFixup(.cond19, @intCast(cond_limit * 4));
    try expectRejectedFixup(.jump26, @intCast(jump_limit * 4));

    // Conditional targets outside imm19 range travel through imm26
    // veneers.  The local inverse branches always skip exactly one
    // instruction and therefore need no fixup of their own.
    var emitter: Emitter = .{
        .arena = testing.allocator,
        .program = undefined,
        .table = undefined,
        .function = undefined,
        .function_index = 0,
    };
    defer emitter.code.deinit(testing.allocator);
    defer emitter.marks.deinit(testing.allocator);
    defer emitter.fixups.deinit(testing.allocator);

    const condition_mark = try emitter.newMark();
    try emitter.branchCond(Emitter.eq, condition_mark);
    const zero_mark = try emitter.newMark();
    try emitter.branchZero(7, zero_mark, true);
    emitter.marks.items[condition_mark] = @intCast(cond_limit * 4);
    emitter.marks.items[zero_mark] = @intCast(cond_limit * 4);
    try emitter.patch();
    try testing.expectEqual(@as(u32, 0x54000041), emittedWord(emitter.code.items, 0)); // b.ne +8
    try testing.expectEqual(@as(u32, 0xB5000047), emittedWord(emitter.code.items, 2)); // cbnz x7, +8
    try testing.expectEqual(@as(usize, 2), emitter.fixups.items.len);
    try testing.expect(emitter.fixups.items[0].kind == .jump26);
    try testing.expect(emitter.fixups.items[1].kind == .jump26);
}

test "the prologue guards depth before SP and links x29" {
    // Golden aarch64 prologue encoding; on x86-64 compile() dispatches
    // to codegen_x86, whose generated code is proven by the two-engine
    // oracle (native_spec.zig) rather than golden bytes.
    if (on_x86) return error.SkipZigTest;
    const source =
        \\func main():
        \\    let answer = 42
        \\
    ;
    var result = try compile_mod.compile(testing.allocator, source, .{}, .{
        .entry_mode = .script,
        .allow_host = true,
    });
    defer result.deinit();
    try testing.expect(result == .success);

    var arena = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena.deinit();
    const spans = try compile(arena.allocator(), &result.success);
    const code = spans[result.success.entry_function];
    try testing.expect(code.len >= 6 * @sizeOf(u32));

    try testing.expectEqual(@as(u32, 0xF9400C0D), emittedWord(code, 0)); // ldr x13, [x0, #24]
    try testing.expectEqual(@as(u32, 0xF10005AD), emittedWord(code, 1)); // subs x13, x13, #1
    try testing.expectEqual(@as(u32, 0xF9000C0D), emittedWord(code, 2)); // str x13, [x0, #24]
    try testing.expectEqual(@as(u32, 0x5400004B), emittedWord(code, 3)); // b.lt +8
    const guarded = emittedWord(code, 4);
    try testing.expectEqual(@as(u32, 0x14000000), guarded & 0xFC000000); // b depth_ok

    var record_at: ?usize = null;
    for (0..code.len / 4) |index| {
        if (emittedWord(code, index) == 0xA9BF7BFD) {
            record_at = index;
            break;
        }
    }
    const frame = record_at orelse return error.TestUnexpectedResult;
    try testing.expect(frame > 4);
    try testing.expectEqual(@as(u32, 0x910003FD), emittedWord(code, frame + 1)); // mov x29, sp

    const raw_displacement = guarded & 0x3FFFFFF;
    const displacement: i64 = if (raw_displacement & (1 << 25) != 0)
        @as(i64, raw_displacement) - (1 << 26)
    else
        raw_displacement;
    try testing.expectEqual(@as(i64, @intCast(frame)), 4 + displacement);
}

test "the gate is MIR's core narrowed by the ABI limits" {
    const whole_language =
        \\import strings
        \\
        \\struct Point:
        \\    x: Float
        \\    y: Float
        \\
        \\func total(p: Point, tail: String) -> Float:
        \\    return p.x + p.y + Float(len(tail))
        \\
        \\func main():
        \\    var xs: List(Int) = [3, 1, 2]
        \\    xs.sort()
        \\    let p = Point(x = 1.5, y = 2.5)
        \\    print(str(total(p, "abc".upper())))
        \\    print(str(xs[0]))
    ;
    const too_many_arguments =
        \\func wide(a: Int, b: Int, c: Int, d: Int, e: Int, f: Int, g: Int, h: Int) -> Int:
        \\    return a + b + c + d + e + f + g + h
        \\
        \\func main():
        \\    print(str(wide(1, 2, 3, 4, 5, 6, 7, 8)))
    ;
    inline for (.{ whole_language, too_many_arguments }, 0..) |source, index| {
        var result = try compile_mod.compile(testing.allocator, source ++ "\n", .{}, .{
            .entry_mode = .script,
            .allow_host = true,
        });
        defer result.deinit();
        try testing.expect(result == .success);
        if (available) {
            try testing.expectEqual(index == 0, supported(&result.success));
        } else {
            try testing.expect(!supported(&result.success));
        }
    }
}
